// Plain-language meanings for the fields of a Hugging Face config.json, in both
// languages. The Config Decoder page reads every field of a model's config through
// this table.
//
// Written from the fields that real configs carry (a sample of 33 across Llama,
// Qwen, DeepSeek, gpt-oss, Gemma, Mistral, Phi, Granite, Nemotron and others), and
// held to one rule: a meaning says only what the field is and what it changes. A
// field this table does not know is shown as unexplained, with its raw value,
// rather than guessed at. A few families of fields (dropout rates, special-token
// ids, Mamba settings) are recognised by their name's pattern; those get a meaning
// that is true of the whole family and nothing more specific.
//
// React-free, so scripts/test-config.ts can hold every entry to both languages.

import type { Lang } from "./dict.ts";

export type FieldGroup =
  | "identity"
  | "shape"
  | "attention"
  | "position"
  | "experts"
  | "hybrid"
  | "vocab"
  | "precision"
  | "vision"
  | "audio"
  | "training"
  | "runtime"
  | "other";

/** Reading order of the field reference. */
export const FIELD_GROUPS: readonly FieldGroup[] = [
  "identity",
  "shape",
  "attention",
  "position",
  "experts",
  "hybrid",
  "vocab",
  "precision",
  "vision",
  "audio",
  "runtime",
  "training",
  "other",
];

/** core: decides memory, speed or context. detail: part of the architecture, but
 *  not a number anyone sizes against. training: has no effect once the model is
 *  trained and served. */
export type Relevance = "core" | "detail" | "training";

/** How a value is turned into words next to its raw form. */
export type ValueKind =
  | "tokens"
  | "count"
  | "number"
  | "bool"
  | "dtype"
  | "act"
  | "ids"
  | "ropeType"
  | "layerTypes"
  | "hybridPattern"
  | "raw";

export type Bi = Record<Lang, string>;

export interface GlossaryEntry {
  group: FieldGroup;
  rel: Relevance;
  title: Bi;
  meaning: Bi;
  kind?: ValueKind;
  /** Unit word after a count, e.g. "layers". */
  unit?: Bi;
  /** What true / false mean for this particular field. */
  yes?: Bi;
  no?: Bi;
}

const bi = (en: string, tr: string): Bi => ({ en, tr });

function e(
  group: FieldGroup,
  rel: Relevance,
  title: [string, string],
  meaning: [string, string],
  extra: Partial<Omit<GlossaryEntry, "group" | "rel" | "title" | "meaning">> = {},
): GlossaryEntry {
  return { group, rel, title: bi(...title), meaning: bi(...meaning), ...extra };
}

const LAYERS = bi("layers", "katman");
const HEADS = bi("heads", "head");
const EXPERTS = bi("experts", "uzman");
const TOKENS_UNIT = bi("tokens", "token");

/** Keyed by the field's own name, or by `parent.child` for fields that only mean
 *  something inside one object (rope_scaling, quantization_config, vision_config). */
export const GLOSSARY: Record<string, GlossaryEntry> = {
  // ── identity & loading ───────────────────────────────────────────────────
  architectures: e("identity", "core",
    ["Architecture class", "Mimari sınıfı"],
    ["The model class these weights were saved from. vLLM picks its own implementation by this name; Transformers' Auto classes go by model_type.",
     "Bu ağırlıkların kaydedildiği model sınıfı. vLLM kendi uygulamasını bu isme göre seçer; Transformers'ın Auto sınıfları ise model_type'a bakar."],
    { kind: "raw" }),
  model_type: e("identity", "core",
    ["Model family", "Model ailesi"],
    ["The family name that tells Transformers which configuration class reads this file. Models of one family share a layout; the numbers in this file are what set them apart.",
     "Transformers'a bu dosyayı hangi yapılandırma sınıfının okuyacağını söyleyen aile adı. Aynı ailedeki modeller aynı yerleşimi paylaşır; onları ayıran bu dosyadaki sayılardır."],
    { kind: "raw" }),
  auto_map: e("runtime", "core",
    ["Custom modelling code", "Özel model kodu"],
    ["Points Transformers at Python files in the repository. Transformers runs that code only with trust_remote_code=True; if the family is also built in, it uses the built-in class unless you opt in. Read the code before you turn that on.",
     "Transformers'ı repodaki Python dosyalarına yönlendirir. Transformers o kodu yalnızca trust_remote_code=True ile çalıştırır; aile yerleşik olarak da varsa, siz istemedikçe yerleşik sınıfı kullanır. Açmadan önce kodu okuyun."]),
  transformers_version: e("runtime", "detail",
    ["Saved with Transformers", "Kaydeden Transformers sürümü"],
    ["The Transformers version that wrote this file. A much older runtime may not know the model family; the number is not a minimum requirement by itself.",
     "Bu dosyayı yazan Transformers sürümü. Çok daha eski bir sürüm model ailesini tanımayabilir; sayı tek başına bir asgari gereksinim değildir."],
    { kind: "raw" }),
  _name_or_path: e("runtime", "detail",
    ["Original name or path", "Özgün ad ya da yol"],
    ["The name or local path the model was loaded from when this file was saved. Informational only.",
     "Bu dosya kaydedilirken modelin yüklendiği ad ya da yerel yol. Yalnızca bilgi amaçlıdır."],
    { kind: "raw" }),
  use_cache: e("runtime", "detail",
    ["Reuse keys and values", "Key ve value'ları yeniden kullan"],
    ["Whether the model hands back keys and values for reuse in the next step. Fine-tuned repos often save false, left over from training; serving engines manage their own cache and ignore it.",
     "Modelin key ve value'ları bir sonraki adımda yeniden kullanılmak üzere döndürüp döndürmediği. İnce ayarlı repolar eğitimden kalma false saklayabilir; sunum motorları önbelleği kendileri yönetir ve bunu yok sayar."],
    { kind: "bool" }),
  cache_implementation: e("runtime", "detail",
    ["Cache class", "Önbellek sınıfı"],
    ["Which cache Transformers uses while generating. 'hybrid' keeps sliding-window layers and full-length layers side by side.",
     "Transformers'ın üretim sırasında kullandığı önbellek. 'hybrid', kayan pencereli katmanlarla tam uzunluklu katmanları yan yana tutar."],
    { kind: "raw" }),
  task_specific_params: e("runtime", "detail",
    ["Task defaults", "Görev varsayılanları"],
    ["Default generation settings for particular tasks, an older Transformers convention. Serving engines ignore them.",
     "Belirli görevler için varsayılan üretim ayarları; eski bir Transformers geleneği. Sunum motorları bunları yok sayar."]),

  // ── shape ─────────────────────────────────────────────────────────────────
  hidden_size: e("shape", "core",
    ["Hidden size", "Hidden boyutu"],
    ["The width of the model: every token travels through the layers as a vector of this many numbers. Weights, activations and most of the compute scale with it.",
     "Modelin genişliği: her token katmanlar boyunca bu kadar sayıdan oluşan bir vektör olarak ilerler. Ağırlıklar, aktivasyonlar ve hesaplamanın çoğu bununla ölçeklenir."],
    { kind: "number" }),
  num_hidden_layers: e("shape", "core",
    ["Layers", "Katman sayısı"],
    ["How many transformer blocks are stacked. Every attention layer keeps its own keys and values, so the KV cache grows in step with this number.",
     "Üst üste dizilen transformer bloğu sayısı. Her attention katmanı kendi key ve value'larını tuttuğu için KV cache bu sayıyla birlikte büyür."],
    { kind: "count", unit: LAYERS }),
  intermediate_size: e("shape", "core",
    ["Feed-forward width", "İleri besleme genişliği"],
    ["The width each token is expanded to inside the feed-forward block before it is projected back to hidden_size. In a dense model this block holds most of the parameters.",
     "Her token'ın ileri besleme bloğunda, yeniden hidden_size'a indirilmeden önce genişletildiği boyut. Yoğun (dense) bir modelde parametrelerin çoğu bu bloktadır."],
    { kind: "number" }),
  hidden_act: e("shape", "detail",
    ["Activation function", "Aktivasyon fonksiyonu"],
    ["The non-linearity inside the feed-forward block. silu here usually means a gated SwiGLU block, with three weight matrices instead of two.",
     "İleri besleme bloğundaki doğrusal olmayan fonksiyon. silu burada genellikle iki yerine üç ağırlık matrisli, kapılı bir SwiGLU bloğu demektir."],
    { kind: "act" }),
  mlp_bias: e("shape", "detail",
    ["Feed-forward bias", "İleri besleme bias'ı"],
    ["Whether the feed-forward projections add a learned bias. A handful of extra parameters, negligible for memory.",
     "İleri besleme projeksiyonlarının öğrenilmiş bir bias ekleyip eklemediği. Birkaç ek parametre; bellek için önemsiz."],
    { kind: "bool" }),
  rms_norm_eps: e("shape", "detail",
    ["Normalization epsilon", "Normalizasyon epsilon'u"],
    ["A tiny constant added inside every RMSNorm layer so it never divides by zero. Part of the arithmetic; it changes neither memory nor speed.",
     "Her RMSNorm katmanına sıfıra bölmemesi için eklenen çok küçük bir sabit. Hesabın parçası; ne belleği ne hızı değiştirir."],
    { kind: "number" }),
  layer_norm_eps: e("shape", "detail",
    ["Normalization epsilon", "Normalizasyon epsilon'u"],
    ["A tiny constant added inside every LayerNorm so it never divides by zero. Part of the arithmetic; it changes neither memory nor speed.",
     "Her LayerNorm'a sıfıra bölmemesi için eklenen çok küçük bir sabit. Hesabın parçası; ne belleği ne hızı değiştirir."],
    { kind: "number" }),
  num_nextn_predict_layers: e("shape", "detail",
    ["Multi-token prediction layers", "Çoklu token tahmin katmanları"],
    ["Extra layers trained to predict tokens further ahead. An engine that supports it can use them for speculative decoding; ordinary serving leaves them out.",
     "Daha ileriki token'ları tahmin etmek için eğitilmiş ek katmanlar. Destekleyen bir motor bunları spekülatif çözümleme için kullanabilir; sıradan sunum bunları dışarıda bırakır."],
    { kind: "count", unit: LAYERS }),
  swiglu_limit: e("shape", "detail",
    ["SwiGLU clamp", "SwiGLU sınırı"],
    ["Clamps the values inside the gated feed-forward block to this magnitude, keeping activations in range. Part of the arithmetic.",
     "Kapılı ileri besleme bloğundaki değerleri bu büyüklükle sınırlar ve aktivasyonları aralıkta tutar. Hesabın parçası."],
    { kind: "number" }),

  // ── attention ─────────────────────────────────────────────────────────────
  num_attention_heads: e("attention", "core",
    ["Attention heads", "Attention head sayısı"],
    ["How many query heads each attention layer runs side by side. Each head can follow a different pattern in the context.",
     "Her attention katmanının yan yana çalıştırdığı query head sayısı. Her head context'te farklı bir örüntüyü izleyebilir."],
    { kind: "count", unit: HEADS }),
  num_key_value_heads: e("attention", "core",
    ["Key-value heads", "Key-value head sayısı"],
    ["How many key and value heads the query heads share. Fewer of them than query heads is grouped-query attention, and the KV cache shrinks by the same ratio.",
     "Query head'lerin paylaştığı key ve value head sayısı. Query head'lerden az olması grouped-query attention demektir ve KV cache aynı oranda küçülür."],
    { kind: "count", unit: HEADS }),
  head_dim: e("attention", "core",
    ["Head dimension", "Head boyutu"],
    ["The length of each attention head's vectors. Without this field it is hidden_size ÷ attention heads; with it, it can differ, and the KV cache uses this value.",
     "Her attention head'inin vektör uzunluğu. Bu alan yoksa hidden_size ÷ attention head alınır; varsa farklı olabilir ve KV cache bu değeri kullanır."],
    { kind: "number" }),
  attention_bias: e("attention", "detail",
    ["Attention bias", "Attention bias'ı"],
    ["Whether the query, key and value projections add a learned bias. A handful of extra parameters, negligible for memory.",
     "Query, key ve value projeksiyonlarının öğrenilmiş bir bias ekleyip eklemediği. Birkaç ek parametre; bellek için önemsiz."],
    { kind: "bool" }),
  kv_lora_rank: e("attention", "core",
    ["Latent KV size (MLA)", "Latent KV boyutu (MLA)"],
    ["The size of the compressed latent that multi-head latent attention caches in place of full keys and values. With qk_rope_head_dim it sets the KV cache per token.",
     "Multi-head latent attention'ın tam key ve value'lar yerine önbellekte tuttuğu sıkıştırılmış latent'in boyutu. qk_rope_head_dim ile birlikte token başına KV cache'i belirler."],
    { kind: "number" }),
  q_lora_rank: e("attention", "detail",
    ["Latent query size (MLA)", "Latent query boyutu (MLA)"],
    ["The size queries are compressed to before they are expanded per head. It saves parameters and activation memory; nothing of it is cached.",
     "Query'lerin head'lere açılmadan önce sıkıştırıldığı boyut. Parametre ve aktivasyon belleği kazandırır; hiçbir kısmı önbelleğe alınmaz."],
    { kind: "number" }),
  qk_rope_head_dim: e("attention", "core",
    ["Positional key size (MLA)", "Konumsal key boyutu (MLA)"],
    ["The part of each query and key that carries rotary position information. This small key is cached next to the latent.",
     "Her query ve key'in rotary konum bilgisini taşıyan kısmı. Bu küçük key, latent'in yanında önbellekte tutulur."],
    { kind: "number" }),
  qk_nope_head_dim: e("attention", "detail",
    ["Non-positional key size (MLA)", "Konumsuz key boyutu (MLA)"],
    ["The part of each query and key without position information. It is rebuilt from the cached latent, so it adds nothing to the cache.",
     "Her query ve key'in konum bilgisi taşımayan kısmı. Önbellekteki latent'ten yeniden üretilir, önbelleğe bir şey eklemez."],
    { kind: "number" }),
  v_head_dim: e("attention", "detail",
    ["Value head size (MLA)", "Value head boyutu (MLA)"],
    ["The length of each value head. Values are rebuilt from the cached latent too.",
     "Her value head'inin uzunluğu. Value'lar da önbellekteki latent'ten yeniden üretilir."],
    { kind: "number" }),
  query_pre_attn_scalar: e("attention", "detail",
    ["Attention scale", "Attention ölçeği"],
    ["Attention scores are divided by the square root of this number instead of the square root of the head dimension.",
     "Attention skorları, head boyutunun karekökü yerine bu sayının kareköküne bölünür."],
    { kind: "number" }),
  attn_logit_softcapping: e("attention", "detail",
    ["Attention soft cap", "Attention yumuşak sınırı"],
    ["Caps attention scores smoothly at this magnitude to keep them stable. null means no cap.",
     "Attention skorlarını kararlı tutmak için bu büyüklükte yumuşakça sınırlar. null, sınır yok demektir."],
    { kind: "number" }),
  use_qk_norm: e("attention", "detail",
    ["Query-key normalization", "Query-key normalizasyonu"],
    ["Whether queries and keys are normalized before attention scores are computed, which stabilizes them.",
     "Attention skorları hesaplanmadan önce query ve key'lerin normalize edilip edilmediği; skorları kararlı kılar."],
    { kind: "bool" }),
  attention_chunk_size: e("attention", "detail",
    ["Attention chunk", "Attention parçası"],
    ["Layers that use chunked attention only attend within blocks of this many tokens.",
     "Parçalı attention kullanan katmanlar yalnızca bu kadar token'lık blokların içine bakar."],
    { kind: "tokens" }),

  // ── position & context ────────────────────────────────────────────────────
  max_position_embeddings: e("position", "core",
    ["Maximum context", "Maksimum context"],
    ["The longest sequence — prompt plus output — the model is configured for. Engines start from it, but their default can differ: vLLM applies the tokenizer's limit and some RoPE settings, and Ollama sizes its default to your VRAM.",
     "Modelin yapılandırıldığı en uzun dizi — istem artı çıktı. Motorlar bundan yola çıkar ama varsayılanları farklı olabilir: vLLM tokenizer sınırını ve bazı RoPE ayarlarını uygular, Ollama varsayılanı VRAM'inize göre seçer."],
    { kind: "tokens" }),
  rope_parameters: e("position", "core",
    ["RoPE settings", "RoPE ayarları"],
    ["Where Transformers v5 keeps the rotary position settings: the base frequency and any scaling, in one object.",
     "Transformers v5'in rotary konum ayarlarını tuttuğu yer: taban frekansı ve varsa ölçekleme, tek bir nesnede."]),
  rope_theta: e("position", "detail",
    ["RoPE base frequency", "RoPE taban frekansı"],
    ["The base of the rotary position embeddings. A larger base makes positions rotate more slowly, one of the ways a model is prepared for long contexts.",
     "Rotary konum embedding'lerinin tabanı. Daha büyük bir taban konumların daha yavaş dönmesini sağlar; bir modeli uzun context'e hazırlamanın yollarından biridir."],
    { kind: "number" }),
  rope_scaling: e("position", "core",
    ["RoPE scaling", "RoPE ölçekleme"],
    ["How rotary positions are rescaled to reach beyond the length they were laid out for: the method, the factor and the original length. null means no rescaling.",
     "Rotary konumların, ilk düzenlendikleri uzunluğun ötesine ulaşmak için nasıl yeniden ölçeklendiği: yöntem, çarpan ve özgün uzunluk. null, yeniden ölçekleme yok demektir."]),
  "rope_scaling.rope_type": e("position", "core",
    ["Scaling method", "Ölçekleme yöntemi"],
    ["The way positions are stretched or split. Each method trades short-range precision against reach differently.",
     "Konumların esnetilme ya da bölünme biçimi. Her yöntem kısa mesafe hassasiyeti ile erişimi farklı dengeler."],
    { kind: "ropeType" }),
  "rope_scaling.factor": e("position", "core",
    ["Stretch factor", "Esnetme çarpanı"],
    ["For linear and YaRN scaling, roughly how many times the original context the positions cover. Llama 3 scaling uses it differently.",
     "Lineer ve YaRN ölçeklemede, konumların özgün context'in yaklaşık kaç katını kapsadığı. Llama 3 ölçeklemesi onu farklı kullanır."],
    { kind: "number" }),
  "rope_scaling.original_max_position_embeddings": e("position", "core",
    ["Original context", "Özgün context"],
    ["The context length the rotary positions were laid out for, before scaling. Model cards usually give it as the pretraining length.",
     "Rotary konumların, ölçeklemeden önce düzenlendiği context uzunluğu. Model kartları genellikle bunu ön eğitim uzunluğu olarak verir."],
    { kind: "tokens" }),
  original_max_position_embeddings: e("position", "detail",
    ["Original context", "Özgün context"],
    ["The context length the positions were laid out for, before any scaling.",
     "Konumların, herhangi bir ölçeklemeden önce düzenlendiği context uzunluğu."],
    { kind: "tokens" }),
  initial_context_length: e("position", "detail",
    ["Initial context", "Başlangıç context'i"],
    ["The context length used before rotary positions were extended.",
     "Rotary konumlar genişletilmeden önce kullanılan context uzunluğu."],
    { kind: "tokens" }),
  "rope_scaling.low_freq_factor": e("position", "detail",
    ["Low-frequency factor", "Düşük frekans çarpanı"],
    ["Llama 3 scaling: rotary wavelengths longer than the original context ÷ this factor are stretched in full.",
     "Llama 3 ölçeklemesi: dalga boyu özgün context ÷ bu çarpandan uzun olan rotary bileşenler tam olarak esnetilir."],
    { kind: "number" }),
  "rope_scaling.high_freq_factor": e("position", "detail",
    ["High-frequency factor", "Yüksek frekans çarpanı"],
    ["Llama 3 scaling: wavelengths shorter than the original context ÷ this factor are left alone; those in between are blended.",
     "Llama 3 ölçeklemesi: dalga boyu özgün context ÷ bu çarpandan kısa olanlara dokunulmaz; aradakiler harmanlanır."],
    { kind: "number" }),
  "rope_scaling.beta_fast": e("position", "detail",
    ["YaRN fast boundary", "YaRN hızlı sınırı"],
    ["YaRN leaves alone the rotary components that turn at least this many times over the original context.",
     "YaRN, özgün context boyunca en az bu kadar tur dönen rotary bileşenlere dokunmaz."],
    { kind: "number" }),
  "rope_scaling.beta_slow": e("position", "detail",
    ["YaRN slow boundary", "YaRN yavaş sınırı"],
    ["YaRN fully interpolates the components that turn fewer than this many times over the original context, and blends those in between.",
     "YaRN, özgün context boyunca bundan az tur dönen bileşenleri tamamen interpolasyonla esnetir, aradakileri harmanlar."],
    { kind: "number" }),
  "rope_scaling.mscale": e("position", "detail",
    ["YaRN temperature", "YaRN sıcaklığı"],
    ["YaRN's correction to attention scores, which keeps them in range as the context is stretched.",
     "YaRN'ın attention skorlarına uyguladığı düzeltme; context esnetildikçe skorları aralıkta tutar."],
    { kind: "number" }),
  "rope_scaling.mscale_all_dim": e("position", "detail",
    ["YaRN temperature (all dims)", "YaRN sıcaklığı (tüm boyutlar)"],
    ["The companion to mscale: the same temperature formula applied to the whole attention score — all of each head's dimensions, not only the rotary ones.",
     "mscale'in eşi: aynı sıcaklık formülü, yalnızca rotary boyutlara değil, her head'in tüm boyutlarına, yani attention skorunun tamamına uygulanır."],
    { kind: "number" }),
  "rope_scaling.truncate": e("position", "detail",
    ["Round YaRN boundaries", "YaRN sınırlarını yuvarla"],
    ["Whether YaRN rounds its frequency boundaries to whole dimensions.",
     "YaRN'ın frekans sınırlarını tam boyutlara yuvarlayıp yuvarlamadığı."],
    { kind: "bool" }),
  "rope_scaling.mrope_section": e("position", "detail",
    ["M-RoPE split", "M-RoPE bölümü"],
    ["How the rotary dimensions are divided between time, height and width, so image and video patches get positions of their own.",
     "Rotary boyutların zaman, yükseklik ve genişlik arasında nasıl bölündüğü; görüntü ve video parçaları böylece kendi konumlarını alır."],
    { kind: "raw" }),
  "rope_scaling.long_factor": e("position", "detail",
    ["Long-input factors", "Uzun girdi çarpanları"],
    ["LongRoPE's per-dimension stretch factors for inputs longer than the original context.",
     "LongRoPE'un özgün context'ten uzun girdiler için boyut başına esnetme çarpanları."],
    { kind: "raw" }),
  "rope_scaling.short_factor": e("position", "detail",
    ["Short-input factors", "Kısa girdi çarpanları"],
    ["LongRoPE's per-dimension factors for inputs within the original context.",
     "LongRoPE'un özgün context içindeki girdiler için boyut başına çarpanları."],
    { kind: "raw" }),
  partial_rotary_factor: e("position", "detail",
    ["Rotary share", "Rotary payı"],
    ["The share of each head's dimensions that carry rotary position information; the rest carry none.",
     "Her head'in boyutlarından rotary konum bilgisi taşıyan pay; geri kalanı konum taşımaz."],
    { kind: "number" }),
  position_embedding_type: e("position", "detail",
    ["Position encoding", "Konum kodlaması"],
    ["How token positions are encoded — absolute, rotary, or 'nope' for no positional embedding at all.",
     "Token konumlarının nasıl kodlandığı — mutlak, rotary ya da hiç konum embedding'i olmayan 'nope'."],
    { kind: "raw" }),
  sliding_window: e("position", "core",
    ["Sliding window", "Kayan pencere"],
    ["Layers that use it attend only to the most recent this-many tokens, so their cache stops growing there. Whether it is on, and in which layers, is set by the fields around it.",
     "Bunu kullanan katmanlar yalnızca son bu kadar token'a bakar; önbellekleri orada büyümeyi bırakır. Etkin olup olmadığını ve hangi katmanlarda olduğunu yanındaki alanlar belirler."],
    { kind: "tokens" }),
  use_sliding_window: e("position", "detail",
    ["Sliding window on", "Kayan pencere açık"],
    ["Whether the sliding window is switched on. When false, sliding_window is ignored.",
     "Kayan pencerenin açık olup olmadığı. false ise sliding_window yok sayılır."],
    { kind: "bool" }),
  max_window_layers: e("position", "detail",
    ["Window layer split", "Pencere katman bölümü"],
    ["How Qwen divides its layers between full attention and the sliding window. It only applies when use_sliding_window is true.",
     "Qwen'in katmanlarını tam attention ile kayan pencere arasında nasıl böldüğü. Yalnızca use_sliding_window true iken geçerlidir."],
    { kind: "count", unit: LAYERS }),
  sliding_window_pattern: e("position", "detail",
    ["Window pattern", "Pencere örüntüsü"],
    ["Every this-many-th layer uses full attention; the others use the sliding window.",
     "Her bu kadarıncı katman tam attention kullanır; diğerleri kayan pencereyi."],
    { kind: "number" }),
  rope_local_base_freq: e("position", "detail",
    ["Local RoPE base", "Yerel RoPE tabanı"],
    ["The rotary base used by the sliding-window layers, separate from the rope_theta of the full-attention ones.",
     "Kayan pencereli katmanların kullandığı rotary taban; tam attention katmanlarının rope_theta'sından ayrıdır."],
    { kind: "number" }),
  no_rope_layers: e("position", "detail",
    ["Layers without RoPE", "RoPE'suz katmanlar"],
    ["Marks, layer by layer, which layers use rotary position embeddings and which do without.",
     "Katman katman, hangi katmanların rotary konum embedding'i kullandığını ve hangilerinin kullanmadığını işaretler."],
    { kind: "raw" }),

  // ── experts ───────────────────────────────────────────────────────────────
  num_experts: e("experts", "core",
    ["Experts", "Uzman sayısı"],
    ["How many expert feed-forward networks each mixture-of-experts layer holds. All of them have to sit in memory, even though a token uses only a few.",
     "Her mixture-of-experts katmanındaki uzman ileri besleme ağı sayısı. Bir token yalnızca birkaçını kullansa da hepsi bellekte durmak zorundadır."],
    { kind: "count", unit: EXPERTS }),
  num_experts_per_tok: e("experts", "core",
    ["Experts per token", "Token başına uzman"],
    ["How many experts the router picks for each token. Compute per token — and so decode speed — follows this number, not the total.",
     "Router'ın her token için seçtiği uzman sayısı. Token başına hesaplama, dolayısıyla çözümleme hızı, toplamı değil bu sayıyı izler."],
    { kind: "count", unit: EXPERTS }),
  moe_intermediate_size: e("experts", "core",
    ["Expert width", "Uzman genişliği"],
    ["The feed-forward width inside each expert — usually far narrower than a dense layer's.",
     "Her uzmanın içindeki ileri besleme genişliği — genellikle yoğun bir katmanınkinden çok daha dar."],
    { kind: "number" }),
  shared_expert_intermediate_size: e("experts", "detail",
    ["Shared expert width", "Ortak uzman genişliği"],
    ["The width of the shared expert every token passes through on top of its routed experts.",
     "Her token'ın seçilen uzmanlarına ek olarak geçtiği ortak uzmanın genişliği."],
    { kind: "number" }),
  n_shared_experts: e("experts", "detail",
    ["Shared experts", "Ortak uzmanlar"],
    ["Experts every token passes through, on top of the ones the router picks.",
     "Router'ın seçtiklerine ek olarak her token'ın geçtiği uzmanlar."],
    { kind: "count", unit: EXPERTS }),
  norm_topk_prob: e("experts", "detail",
    ["Renormalize router weights", "Router ağırlıklarını yeniden normalize et"],
    ["Whether the chosen experts' router weights are rescaled to add up to one.",
     "Seçilen uzmanların router ağırlıklarının toplamı bir olacak şekilde yeniden ölçeklenip ölçeklenmediği."],
    { kind: "bool" }),
  decoder_sparse_step: e("experts", "detail",
    ["Expert layer step", "Uzman katman adımı"],
    ["Every this-many-th layer is a mixture-of-experts layer; 1 means all of them.",
     "Her bu kadarıncı katman bir mixture-of-experts katmanıdır; 1, hepsi demektir."],
    { kind: "number" }),
  mlp_only_layers: e("experts", "detail",
    ["Dense-only layers", "Yalnız yoğun katmanlar"],
    ["Layers that keep a dense feed-forward block instead of experts. Empty means none.",
     "Uzman yerine yoğun bir ileri besleme bloğu tutan katmanlar. Boşsa hiçbiri."],
    { kind: "raw" }),
  first_k_dense_replace: e("experts", "detail",
    ["Leading dense layers", "Baştaki yoğun katmanlar"],
    ["The first this-many layers use a dense feed-forward block; experts start after them.",
     "İlk bu kadar katman yoğun ileri besleme bloğu kullanır; uzmanlar onlardan sonra başlar."],
    { kind: "count", unit: LAYERS }),
  moe_layer_freq: e("experts", "detail",
    ["Expert layer frequency", "Uzman katman sıklığı"],
    ["After the leading dense layers, every this-many-th layer is a mixture-of-experts layer.",
     "Baştaki yoğun katmanlardan sonra her bu kadarıncı katman bir mixture-of-experts katmanıdır."],
    { kind: "number" }),
  interleave_moe_layer_step: e("experts", "detail",
    ["Expert layer step", "Uzman katman adımı"],
    ["Every this-many-th layer is a mixture-of-experts layer; the rest are dense.",
     "Her bu kadarıncı katman bir mixture-of-experts katmanıdır; kalanlar yoğundur."],
    { kind: "number" }),
  moe_layers: e("experts", "detail",
    ["Expert layers", "Uzman katmanları"],
    ["The layers that are mixture-of-experts layers.",
     "Mixture-of-experts olan katmanlar."],
    { kind: "raw" }),
  routed_scaling_factor: e("experts", "detail",
    ["Routed output scale", "Seçilen uzman çıktı ölçeği"],
    ["A multiplier on the routed experts' combined output.",
     "Seçilen uzmanların birleşik çıktısına uygulanan çarpan."],
    { kind: "number" }),
  scoring_func: e("experts", "detail",
    ["Router scoring", "Router puanlaması"],
    ["How the router turns its scores into weights — softmax or sigmoid.",
     "Router'ın puanlarını ağırlıklara nasıl çevirdiği — softmax ya da sigmoid."],
    { kind: "raw" }),
  topk_method: e("experts", "detail",
    ["Routing rule", "Yönlendirme kuralı"],
    ["How the router chooses experts. noaux_tc is DeepSeek-V3's group-limited routing, which balances experts mainly with a per-expert bias on the router scores rather than an auxiliary loss.",
     "Router'ın uzmanları nasıl seçtiği. noaux_tc, DeepSeek-V3'ün grup sınırlı yönlendirmesidir; uzmanları yardımcı bir kayıptan çok, router skorlarına eklenen uzman başına bir sapmayla dengeler."],
    { kind: "raw" }),
  n_group: e("experts", "detail",
    ["Expert groups", "Uzman grupları"],
    ["Group-limited routing splits the experts into this many groups; a token may only use experts from its best few groups, which limits traffic between devices.",
     "Grup sınırlı yönlendirme uzmanları bu kadar gruba böler; bir token yalnızca en iyi birkaç grubundaki uzmanları kullanabilir, bu da cihazlar arası trafiği sınırlar."],
    { kind: "number" }),
  topk_group: e("experts", "detail",
    ["Groups per token", "Token başına grup"],
    ["How many of those groups each token may draw its experts from.",
     "Her token'ın uzmanlarını bu gruplardan kaç tanesinden seçebileceği."],
    { kind: "number" }),
  ep_size: e("experts", "detail",
    ["Recorded expert parallelism", "Kayıtlı uzman paralelliği"],
    ["The expert-parallel degree DeepSeek's own modelling code expects at load time (1 means one process). Other engines ignore it and choose their own.",
     "DeepSeek'in kendi model kodunun yüklemede beklediği uzman paralellik derecesi (1, tek süreç demektir). Diğer motorlar bunu yok sayar ve kendilerininkini seçer."],
    { kind: "number" }),

  // ── hybrid layers ─────────────────────────────────────────────────────────
  layer_types: e("hybrid", "core",
    ["Layer types", "Katman türleri"],
    ["The kind of every layer, in order. Sliding-window, linear-attention and state-space layers keep a bounded cache; full-attention layers keep every token.",
     "Her katmanın türü, sırasıyla. Kayan pencereli, lineer attention ve durum uzayı katmanları sınırlı bir önbellek tutar; tam attention katmanları her token'ı tutar."],
    { kind: "layerTypes" }),
  layers_block_type: e("hybrid", "core",
    ["Layer types", "Katman türleri"],
    ["The kind of every layer, in order, as Transformers v5 writes it for Nemotron-H. Only the attention layers keep a KV cache.",
     "Her katmanın türü, sırasıyla; Transformers v5'in Nemotron-H için yazdığı biçimde. Yalnızca attention katmanları KV cache tutar."],
    { kind: "layerTypes" }),
  full_attn_idxs: e("hybrid", "core",
    ["Attention layers", "Attention katmanları"],
    ["The layers that use full attention; the others are short-convolution layers with a fixed-size state.",
     "Tam attention kullanan katmanlar; diğerleri sabit boyutlu bir durum tutan kısa konvolüsyon katmanlarıdır."],
    { kind: "raw" }),
  full_attention_interval: e("hybrid", "core",
    ["Full-attention interval", "Tam attention aralığı"],
    ["Every this-many-th layer uses full attention; the layers between use linear attention, which keeps a fixed-size state instead of a growing cache.",
     "Her bu kadarıncı katman tam attention kullanır; aradakiler büyüyen bir önbellek yerine sabit boyutlu bir durum tutan lineer attention kullanır."],
    { kind: "number" }),
  hybrid_override_pattern: e("hybrid", "core",
    ["Layer pattern", "Katman örüntüsü"],
    ["One character per layer: M is a Mamba (state-space) layer, * an attention layer, - a feed-forward layer, E a mixture-of-experts layer. Only the attention layers keep a KV cache.",
     "Katman başına bir karakter: M bir Mamba (durum uzayı) katmanı, * bir attention katmanı, - bir ileri besleme katmanı, E bir mixture-of-experts katmanı. Yalnızca attention katmanları KV cache tutar."],
    { kind: "hybridPattern" }),
  attn_layer_indices: e("hybrid", "core",
    ["Attention layers", "Attention katmanları"],
    ["The layers that include attention.",
     "Attention içeren katmanlar."],
    { kind: "raw" }),

  // ── vocabulary & tokens ───────────────────────────────────────────────────
  vocab_size: e("vocab", "core",
    ["Vocabulary size", "Kelime dağarcığı"],
    ["How many rows the embedding table holds — the tokenizer's vocabulary, often padded to a round number. The input embedding and the output projection are each vocab_size × hidden_size.",
     "Embedding tablosunun satır sayısı — tokenizer'ın kelime dağarcığı, çoğu zaman yuvarlak bir sayıya tamamlanmış. Giriş embedding'i ve çıkış projeksiyonu her biri vocab_size × hidden_size boyutundadır."],
    { kind: "number" }),
  tie_word_embeddings: e("vocab", "core",
    ["Tied embeddings", "Paylaşılan embedding'ler"],
    ["Whether the input embedding table and the output projection share one matrix. Tied saves vocab_size × hidden_size parameters; untied keeps two.",
     "Giriş embedding tablosu ile çıkış projeksiyonunun tek bir matrisi paylaşıp paylaşmadığı. Paylaşılırsa vocab_size × hidden_size parametre kazanılır; paylaşılmazsa iki matris tutulur."],
    { kind: "bool", yes: bi("Yes — one shared matrix", "Evet — tek ortak matris"), no: bi("No — two separate matrices", "Hayır — iki ayrı matris") }),
  bos_token_id: e("vocab", "detail",
    ["Start-of-sequence token", "Dizi başı token'ı"],
    ["The id of the token placed at the start of a sequence.",
     "Dizinin başına konan token'ın kimliği."],
    { kind: "ids" }),
  eos_token_id: e("vocab", "detail",
    ["End-of-sequence token", "Dizi sonu token'ı"],
    ["The id, or ids, of the token that ends generation. With a list, any one of them stops the reply. The repo's generation_config.json can override it.",
     "Üretimi bitiren token'ın kimliği ya da kimlikleri. Liste ise herhangi biri yanıtı durdurur. Reponun generation_config.json dosyası bunu geçersiz kılabilir."],
    { kind: "ids" }),
  pad_token_id: e("vocab", "detail",
    ["Padding token", "Dolgu token'ı"],
    ["The id used to pad the sequences of a batch to equal length.",
     "Bir batch'teki dizileri eşit uzunluğa getirmek için kullanılan kimlik."],
    { kind: "ids" }),
  unk_token_id: e("vocab", "detail",
    ["Unknown token", "Bilinmeyen token"],
    ["The id standing in for text the tokenizer cannot encode.",
     "Tokenizer'ın kodlayamadığı metnin yerini tutan kimlik."],
    { kind: "ids" }),
  final_logit_softcapping: e("vocab", "detail",
    ["Output soft cap", "Çıktı yumuşak sınırı"],
    ["Caps the output scores over the vocabulary smoothly at this magnitude. null means no cap.",
     "Kelime dağarcığı üzerindeki çıktı skorlarını bu büyüklükte yumuşakça sınırlar. null, sınır yok demektir."],
    { kind: "number" }),

  // ── precision & quantization ──────────────────────────────────────────────
  torch_dtype: e("precision", "core",
    ["Stored precision", "Saklanan hassasiyet"],
    ["The precision the weights were saved in: bfloat16 and float16 take 2 bytes a parameter, float32 takes 4. In a quantized repo it covers only the parts left unquantized.",
     "Ağırlıkların kaydedildiği hassasiyet: bfloat16 ve float16 parametre başına 2 bayt, float32 4 bayt tutar. Quantize edilmiş bir repoda yalnızca quantize edilmeyen kısımları kapsar."],
    { kind: "dtype" }),
  quantization_config: e("precision", "core",
    ["Quantization", "Quantization"],
    ["How the weights were compressed below their stored precision. Its presence means the checkpoint is already quantized, and the serving engine has to support the method named inside.",
     "Ağırlıkların saklanan hassasiyetin altına nasıl sıkıştırıldığı. Varlığı checkpoint'in zaten quantize edildiği anlamına gelir; sunum motoru içindeki yöntemi desteklemelidir."]),
  "quantization_config.quant_method": e("precision", "core",
    ["Quantization method", "Quantization yöntemi"],
    ["The scheme — for example awq, gptq, fp8, mxfp4, bitsandbytes or compressed-tensors. Serving engines choose their kernels from this.",
     "Şema — örneğin awq, gptq, fp8, mxfp4, bitsandbytes ya da compressed-tensors. Sunum motorları çekirdeklerini buna göre seçer."],
    { kind: "raw" }),
  "quantization_config.bits": e("precision", "core",
    ["Bits per weight", "Ağırlık başına bit"],
    ["How many bits each quantized weight takes.",
     "Her quantize edilmiş ağırlığın kaç bit tuttuğu."],
    { kind: "number" }),
  "quantization_config.group_size": e("precision", "detail",
    ["Group size", "Grup boyutu"],
    ["How many consecutive weights share one scale. Smaller groups are more accurate and cost a little more memory; -1 means one scale per output channel, with no grouping.",
     "Kaç ardışık ağırlığın tek bir ölçeği paylaştığı. Küçük gruplar daha doğrudur ve biraz daha fazla bellek tutar; -1, gruplama olmadan çıkış kanalı başına tek ölçek demektir."],
    { kind: "number" }),
  "quantization_config.zero_point": e("precision", "detail",
    ["Zero point", "Sıfır noktası"],
    ["Whether each group also stores an offset (asymmetric quantization).",
     "Her grubun ayrıca bir kaydırma değeri saklayıp saklamadığı (asimetrik quantization)."],
    { kind: "bool" }),
  "quantization_config.version": e("precision", "detail",
    ["Kernel layout", "Çekirdek yerleşimi"],
    ["The layout the weights were packed for, such as AWQ's gemm or gemv kernels.",
     "Ağırlıkların paketlendiği yerleşim; örneğin AWQ'nun gemm ya da gemv çekirdekleri."],
    { kind: "raw" }),
  "quantization_config.desc_act": e("precision", "detail",
    ["Activation order", "Aktivasyon sırası"],
    ["Whether GPTQ quantized columns in order of activation size — usually more accurate, sometimes slower.",
     "GPTQ'nun sütunları aktivasyon büyüklüğü sırasıyla quantize edip etmediği — genellikle daha doğru, bazen daha yavaş."],
    { kind: "bool" }),
  "quantization_config.sym": e("precision", "detail",
    ["Symmetric", "Simetrik"],
    ["Whether quantization is symmetric around zero, with no offset stored.",
     "Quantization'ın sıfır etrafında simetrik olup olmadığı; kaydırma saklanmaz."],
    { kind: "bool" }),
  "quantization_config.fmt": e("precision", "detail",
    ["FP8 layout", "FP8 yerleşimi"],
    ["The FP8 bit layout: e4m3 keeps more precision, e5m2 more range.",
     "FP8 bit yerleşimi: e4m3 daha fazla hassasiyet, e5m2 daha geniş aralık tutar."],
    { kind: "raw" }),
  "quantization_config.activation_scheme": e("precision", "detail",
    ["Activation scaling", "Aktivasyon ölçekleme"],
    ["How activations are quantized: dynamic computes their scales on the fly for each input, static uses scales fixed at calibration.",
     "Aktivasyonların nasıl quantize edildiği: dynamic ölçekleri her girdi için anında hesaplar, static kalibrasyonda sabitlenen ölçekleri kullanır."],
    { kind: "raw" }),
  "quantization_config.weight_block_size": e("precision", "detail",
    ["Scaling block", "Ölçekleme bloğu"],
    ["The weights are scaled in blocks of this shape, one scale per block.",
     "Ağırlıklar bu şekildeki bloklar halinde ölçeklenir; blok başına bir ölçek."],
    { kind: "raw" }),
  "quantization_config.modules_to_not_convert": e("precision", "detail",
    ["Left unquantized", "Quantize edilmeyenler"],
    ["Modules kept at the stored precision — commonly the embeddings and the output head, sometimes attention or the router.",
     "Saklanan hassasiyette bırakılan modüller — genellikle embedding'ler ve çıkış katmanı, bazen attention ya da router."],
    { kind: "raw" }),
  "quantization_config.ignore": e("precision", "detail",
    ["Left unquantized", "Quantize edilmeyenler"],
    ["Layers kept at the stored precision, most often the output head.",
     "Saklanan hassasiyette bırakılan katmanlar; çoğunlukla çıkış katmanı."],
    { kind: "raw" }),
  "quantization_config.config_groups": e("precision", "detail",
    ["Quantization recipes", "Quantization tarifleri"],
    ["compressed-tensors' per-layer recipes: the bits, number type and granularity used for weights and for activations.",
     "compressed-tensors'un katman başına tarifleri: ağırlıklar ve aktivasyonlar için kullanılan bit sayısı, sayı türü ve ayrıntı düzeyi."]),
  "quantization_config.kv_cache_scheme": e("precision", "core",
    ["KV cache precision", "KV cache hassasiyeti"],
    ["Calibrated scales for a lower-precision KV cache, usually 8-bit. An engine told to use them stores the cache at that precision instead of 16-bit.",
     "Daha düşük hassasiyetli bir KV cache için kalibre edilmiş ölçekler, genellikle 8 bit. Bunları kullanması söylenen bir motor önbelleği 16 bit yerine o hassasiyette tutar."]),
  "quantization_config.format": e("precision", "detail",
    ["Packing format", "Paketleme biçimi"],
    ["compressed-tensors' packing format, naming how the numbers are stored.",
     "compressed-tensors'un paketleme biçimi; sayıların nasıl saklandığını adlandırır."],
    { kind: "raw" }),
  "quantization_config.quantization_status": e("precision", "detail",
    ["Status", "Durum"],
    ["Where the checkpoint is in compressed-tensors' lifecycle; 'compressed' means the weights are stored packed.",
     "Checkpoint'in compressed-tensors yaşam döngüsündeki yeri; 'compressed', ağırlıkların paketlenmiş saklandığı demektir."],
    { kind: "raw" }),
  "quantization_config.global_compression_ratio": e("precision", "detail",
    ["Compression ratio", "Sıkıştırma oranı"],
    ["The size reduction recorded when the checkpoint was compressed.",
     "Checkpoint sıkıştırılırken kaydedilen boyut azalması."],
    { kind: "number" }),
  "quantization_config.load_in_4bit": e("precision", "core",
    ["4-bit loading", "4 bit yükleme"],
    ["bitsandbytes loads the weights in 4 bits.",
     "bitsandbytes ağırlıkları 4 bitte yükler."],
    { kind: "bool" }),
  "quantization_config.load_in_8bit": e("precision", "core",
    ["8-bit loading", "8 bit yükleme"],
    ["bitsandbytes loads the weights in 8 bits.",
     "bitsandbytes ağırlıkları 8 bitte yükler."],
    { kind: "bool" }),
  "quantization_config.bnb_4bit_quant_type": e("precision", "detail",
    ["4-bit format", "4 bit biçimi"],
    ["The 4-bit number format bitsandbytes uses — nf4 (normal float) or fp4.",
     "bitsandbytes'ın kullandığı 4 bitlik sayı biçimi — nf4 (normal float) ya da fp4."],
    { kind: "raw" }),
  "quantization_config.bnb_4bit_compute_dtype": e("precision", "detail",
    ["Compute precision", "Hesaplama hassasiyeti"],
    ["The precision bitsandbytes computes in once each 4-bit block is unpacked.",
     "Her 4 bitlik blok açıldıktan sonra bitsandbytes'ın hesapladığı hassasiyet."],
    { kind: "raw" }),
  "quantization_config.bnb_4bit_use_double_quant": e("precision", "detail",
    ["Double quantization", "Çift quantization"],
    ["Whether the per-block scales are themselves quantized, saving about 0.37 bits per parameter.",
     "Blok başına ölçeklerin de quantize edilip edilmediği; parametre başına yaklaşık 0,37 bit kazandırır."],
    { kind: "bool" }),

  // ── vision & audio ────────────────────────────────────────────────────────
  text_config: e("identity", "core",
    ["Language model", "Dil modeli"],
    ["The language model inside a multimodal model. Its fields are read with the other language-model fields on this page.",
     "Çok kipli bir modelin içindeki dil modeli. Alanları bu sayfada diğer dil modeli alanlarıyla birlikte okunur."]),
  vision_config: e("vision", "core",
    ["Vision encoder", "Görüntü kodlayıcı"],
    ["A separate, smaller transformer that turns an image into tokens the language model can read. Its weights add to the model's memory.",
     "Bir görüntüyü dil modelinin okuyabileceği token'lara çeviren ayrı, daha küçük bir transformer. Ağırlıkları modelin belleğine eklenir."]),
  audio_config: e("audio", "core",
    ["Audio encoder", "Ses kodlayıcı"],
    ["The encoder that turns sound into tokens for the language model. Its weights add to the model's memory.",
     "Sesi dil modeli için token'lara çeviren kodlayıcı. Ağırlıkları modelin belleğine eklenir."]),
  mm_tokens_per_image: e("vision", "core",
    ["Tokens per image", "Görüntü başına token"],
    ["How many tokens each image becomes in the language model's context — and in its KV cache.",
     "Her görüntünün dil modelinin context'inde — ve KV cache'inde — kaç token'a dönüştüğü."],
    { kind: "count", unit: TOKENS_UNIT }),
  image_token_index: e("vision", "detail",
    ["Image placeholder token", "Görüntü yer tutucu token'ı"],
    ["The id of the placeholder token where an image's embeddings are inserted into the text.",
     "Bir görüntünün embedding'lerinin metne yerleştirildiği yer tutucu token'ın kimliği."],
    { kind: "ids" }),
  video_token_id: e("vision", "detail",
    ["Video placeholder token", "Video yer tutucu token'ı"],
    ["The id of the placeholder token where a video's embeddings are inserted into the text.",
     "Bir videonun embedding'lerinin metne yerleştirildiği yer tutucu token'ın kimliği."],
    { kind: "ids" }),
  vision_feature_layer: e("vision", "detail",
    ["Feature layer", "Özellik katmanı"],
    ["Which layer of the vision encoder the image features are taken from.",
     "Görüntü özelliklerinin görüntü kodlayıcının hangi katmanından alındığı."],
    { kind: "raw" }),
  projector_hidden_act: e("vision", "detail",
    ["Projector activation", "Projektör aktivasyonu"],
    ["The activation in the small projector that maps image features into the language model's width.",
     "Görüntü özelliklerini dil modelinin genişliğine eşleyen küçük projektördeki aktivasyon."],
    { kind: "act" }),
  multimodal_projector_bias: e("vision", "detail",
    ["Projector bias", "Projektör bias'ı"],
    ["Whether that projector adds a learned bias.",
     "Bu projektörün öğrenilmiş bir bias ekleyip eklemediği."],
    { kind: "bool" }),
  "vision_config.patch_size": e("vision", "detail",
    ["Patch size", "Parça boyutu"],
    ["Images are cut into square patches this many pixels wide; each patch becomes one vector.",
     "Görüntüler bu kadar piksel genişliğinde kare parçalara bölünür; her parça bir vektör olur."],
    { kind: "number" }),
  "vision_config.image_size": e("vision", "detail",
    ["Image size", "Görüntü boyutu"],
    ["The image resolution the encoder works at, in pixels per side.",
     "Kodlayıcının çalıştığı görüntü çözünürlüğü, kenar başına piksel."],
    { kind: "number" }),
  "vision_config.num_channels": e("vision", "detail",
    ["Colour channels", "Renk kanalları"],
    ["Colour channels per pixel; 3 is RGB.",
     "Piksel başına renk kanalı; 3, RGB demektir."],
    { kind: "number" }),
  "vision_config.out_hidden_size": e("vision", "detail",
    ["Output width", "Çıkış genişliği"],
    ["The width vision features are projected to before the language model reads them.",
     "Görüntü özelliklerinin dil modeli okumadan önce yansıtıldığı genişlik."],
    { kind: "number" }),
  "vision_config.spatial_merge_size": e("vision", "detail",
    ["Patch merging", "Parça birleştirme"],
    ["Neighbouring patches are merged in squares of this side before they reach the language model, cutting the token count.",
     "Komşu parçalar dil modeline ulaşmadan önce bu kenar uzunluğunda karelerde birleştirilir; token sayısı azalır."],
    { kind: "number" }),

  // ── training only ─────────────────────────────────────────────────────────
  initializer_range: e("training", "training",
    ["Initialization spread", "Başlangıç dağılımı"],
    ["The spread of the random values weights started from before training. It has no effect on a trained model.",
     "Ağırlıkların eğitimden önce başladığı rastgele değerlerin dağılımı. Eğitilmiş bir modelde etkisi yoktur."],
    { kind: "number" }),
  router_aux_loss_coef: e("training", "training",
    ["Load-balancing loss weight", "Yük dengeleme kaybı ağırlığı"],
    ["How strongly training pushed the router to use every expert evenly. No effect when serving.",
     "Eğitimin router'ı her uzmanı eşit kullanmaya ne kadar zorladığı. Sunumda etkisi yoktur."],
    { kind: "number" }),
  aux_loss_alpha: e("training", "training",
    ["Load-balancing loss weight", "Yük dengeleme kaybı ağırlığı"],
    ["How strongly training pushed the router to use every expert evenly. No effect when serving.",
     "Eğitimin router'ı her uzmanı eşit kullanmaya ne kadar zorladığı. Sunumda etkisi yoktur."],
    { kind: "number" }),
  output_router_logits: e("training", "training",
    ["Return router scores", "Router skorlarını döndür"],
    ["Whether the model hands back its router scores so the balancing loss can be computed — a training switch.",
     "Dengeleme kaybı hesaplanabilsin diye modelin router skorlarını döndürüp döndürmediği — bir eğitim anahtarı."],
    { kind: "bool" }),
  router_jitter_noise: e("training", "training",
    ["Router noise", "Router gürültüsü"],
    ["Noise added to router scores during training to spread the load. Off at inference.",
     "Yükü yaymak için eğitimde router skorlarına eklenen gürültü. Çıkarımda kapalıdır."],
    { kind: "number" }),
  seq_aux: e("training", "training",
    ["Per-sequence balancing", "Dizi başına dengeleme"],
    ["Whether the balancing loss was computed per sequence. Training only.",
     "Dengeleme kaybının dizi başına hesaplanıp hesaplanmadığı. Yalnızca eğitim."],
    { kind: "bool" }),
  pretraining_tp: e("training", "training",
    ["Pretraining tensor parallelism", "Ön eğitim tensör paralelliği"],
    ["The tensor-parallel degree used in pretraining, kept for exact reproduction. It has nothing to do with how many GPUs you serve on.",
     "Ön eğitimde kullanılan tensör paralellik derecesi; birebir yeniden üretim için saklanır. Kaç GPU'da sunacağınızla ilgisi yoktur."],
    { kind: "number" }),
};

/** Other spellings of the same field, as different families write them. */
export const ALIASES: Record<string, string> = {
  n_embd: "hidden_size",
  n_embed: "hidden_size",
  d_model: "hidden_size",
  n_layer: "num_hidden_layers",
  num_layers: "num_hidden_layers",
  depth: "num_hidden_layers",
  n_head: "num_attention_heads",
  num_heads: "num_attention_heads",
  num_kv_heads: "num_key_value_heads",
  n_inner: "intermediate_size",
  ffn_dim: "intermediate_size",
  hidden_activation: "hidden_act",
  activation_function: "hidden_act",
  layer_norm_epsilon: "layer_norm_eps",
  n_positions: "max_position_embeddings",
  n_ctx: "max_position_embeddings",
  max_seq_len: "max_position_embeddings",
  rotary_emb_base: "rope_theta",
  rotary_pct: "partial_rotary_factor",
  num_local_experts: "num_experts",
  n_routed_experts: "num_experts",
  moe_num_experts: "num_experts",
  experts_per_token: "num_experts_per_tok",
  moe_top_k: "num_experts_per_tok",
  shared_intermediate_size: "shared_expert_intermediate_size",
  dtype: "torch_dtype",
  image_token_id: "image_token_index",
  "rope_scaling.type": "rope_scaling.rope_type",
  "quantization_config.llm_int8_skip_modules": "quantization_config.modules_to_not_convert",
};

/** Families of fields recognised by name. Their meanings are true of every member,
 *  and say nothing more specific than that. */
export const PATTERNS: { test: RegExp; entry: GlossaryEntry }[] = [
  {
    test: /(dropout|_pdrop)$/,
    entry: e("training", "training",
      ["Dropout rate", "Dropout oranı"],
      ["The share of values randomly zeroed during training. Inference switches dropout off, so it has no effect when serving.",
       "Eğitimde rastgele sıfırlanan değerlerin payı. Çıkarım dropout'u kapatır; sunumda etkisi yoktur."],
      { kind: "number" }),
  },
  {
    test: /_token_(id|index)$/,
    entry: e("vocab", "detail",
      ["Special token", "Özel token"],
      ["The id of a special token in the tokenizer's vocabulary.",
       "Tokenizer'ın kelime dağarcığındaki özel bir token'ın kimliği."],
      { kind: "ids" }),
  },
  {
    test: /^(mamba|ssm|time_step)|^conv_kernel$/,
    entry: e("hybrid", "detail",
      ["State-space layer setting", "Durum uzayı katmanı ayarı"],
      ["A setting of the model's state-space (Mamba) layers, which keep a fixed-size state per sequence instead of a cache that grows with every token.",
       "Modelin durum uzayı (Mamba) katmanlarının bir ayarı; bu katmanlar her token'la büyüyen bir önbellek yerine dizi başına sabit boyutlu bir durum tutar."]),
  },
  {
    test: /^linear_/,
    entry: e("hybrid", "detail",
      ["Linear-attention setting", "Lineer attention ayarı"],
      ["A setting of the model's linear-attention layers, which keep a fixed-size state instead of a growing cache.",
       "Modelin lineer attention katmanlarının bir ayarı; bu katmanlar büyüyen bir önbellek yerine sabit boyutlu bir durum tutar."]),
  },
  {
    test: /^summary_/,
    entry: e("training", "training",
      ["Classification head setting", "Sınıflandırma başlığı ayarı"],
      ["A setting of an optional classification head, used only when the model is fine-tuned for classification.",
       "İsteğe bağlı bir sınıflandırma başlığının ayarı; yalnızca model sınıflandırma için ince ayarlanırken kullanılır."]),
  },
  {
    test: /^unsloth_/,
    entry: e("runtime", "detail",
      ["Unsloth marker", "Unsloth işareti"],
      ["A marker left by Unsloth, the tool that re-uploaded or patched this repository. It does not change the model.",
       "Bu repoyu yeniden yükleyen ya da düzelten Unsloth aracının bıraktığı işaret. Modeli değiştirmez."]),
  },
  {
    // Not the FFN-width multipliers (LFM2's block_ffn_dim_multiplier sizes a layer).
    test: /^(?!.*ffn).*multiplier$/,
    entry: e("shape", "detail",
      ["Scaling constant", "Ölçekleme sabiti"],
      ["A fixed multiplier inside the model's arithmetic.",
       "Modelin hesabındaki sabit bir çarpan."],
      { kind: "number" }),
  },
  {
    test: /_bias$/,
    entry: e("shape", "detail",
      ["Bias term", "Bias terimi"],
      ["Whether these layers add a learned bias. A handful of extra parameters, negligible for memory.",
       "Bu katmanların öğrenilmiş bir bias ekleyip eklemediği. Birkaç ek parametre; bellek için önemsiz."],
      { kind: "bool" }),
  },
];

export interface GlossaryHit {
  entry: GlossaryEntry;
  match: "exact" | "pattern";
}

/** The meaning of a field, given its parent object ("" at the top level, or
 *  "rope_scaling", "vision_config"…) and its own name. text_config is the language
 *  model itself, so its children read as top-level fields. */
export function lookupField(parent: string, key: string): GlossaryHit | null {
  const scope = parent === "rope_parameters" ? "rope_scaling" : parent;
  const scoped = scope && scope !== "text_config" && scope !== "llm_config" ? `${scope}.${key}` : "";
  const candidates = [scoped, scoped && ALIASES[scoped], key, ALIASES[key]].filter(Boolean) as string[];
  for (const c of candidates) {
    const hit = GLOSSARY[c];
    if (hit) return { entry: hit, match: "exact" };
  }
  for (const p of PATTERNS) if (p.test.test(key)) return { entry: p.entry, match: "pattern" };
  return null;
}

export const GROUP_LABEL: Record<FieldGroup, Bi> = {
  identity: bi("What the model is", "Model ne"),
  shape: bi("Size and shape", "Boyut ve şekil"),
  attention: bi("Attention", "Attention"),
  position: bi("Positions and context", "Konumlar ve context"),
  experts: bi("Mixture of experts", "Mixture of experts"),
  hybrid: bi("Hybrid layers", "Hibrit katmanlar"),
  vocab: bi("Vocabulary and special tokens", "Kelime dağarcığı ve özel token'lar"),
  precision: bi("Precision and quantization", "Hassasiyet ve quantization"),
  vision: bi("Vision encoder", "Görüntü kodlayıcı"),
  audio: bi("Audio encoder", "Ses kodlayıcı"),
  runtime: bi("Loading and runtime", "Yükleme ve çalışma"),
  training: bi("Only used in training", "Yalnızca eğitimde kullanılır"),
  other: bi("Not in the glossary yet", "Henüz sözlükte yok"),
};

export const GROUP_NOTE: Partial<Record<FieldGroup, Bi>> = {
  vision: bi(
    "These fields belong to the image encoder, not the language model. They add weights, but not KV cache per text token.",
    "Bu alanlar dil modeline değil, görüntü kodlayıcıya aittir. Ağırlık eklerler ama metin token'ı başına KV cache eklemezler.",
  ),
  audio: bi(
    "These fields belong to the audio encoder, not the language model.",
    "Bu alanlar dil modeline değil, ses kodlayıcıya aittir.",
  ),
  training: bi(
    "Serving can ignore everything here: these fields steered training and have no effect on a trained model's memory, speed or output.",
    "Sunum buradaki her şeyi yok sayabilir: bu alanlar eğitimi yönlendirdi ve eğitilmiş bir modelin belleğini, hızını ya da çıktısını etkilemez.",
  ),
  other: bi(
    "LLMScale does not explain these fields yet, so it shows them exactly as the file has them rather than guess.",
    "LLMScale bu alanları henüz açıklamıyor; tahmin etmek yerine dosyada nasılsa öyle gösteriyor.",
  ),
};
