// Translation data and the pure lookup. Kept free of React so scripts can
// import it directly (node scripts/test-invariants.ts).
export type Lang = "en" | "tr";

type Dict = Record<string, string>;

const en: Dict = {
  "header.badge": "live Hugging Face data",
  "header.subtitle":
    "How much GPU memory does a model really need? Weights and KV cache scale with your {ctx} and {users}. Pick a model, tune the workload, and see which GPUs fit.",
  "header.subtitle.ctx": "context window",
  "header.subtitle.users": "concurrent users",
  "header.share": "Share this estimate",
  "header.shareCopied": "Link copied ✓",
  "results.empty": "Pick a model to see the VRAM breakdown.",
  "results.emptyHint":
    "Weights, KV cache and overhead are computed in your browser from the model's own config — search Hugging Face above, or start from a preset.",

  "model.step": "Choose a model",
  "model.tab.search": "Search Hugging Face",
  "model.tab.presets": "Presets",
  "model.tab.custom": "Custom",
  "model.search.placeholder": "e.g. Qwen/Qwen2.5-7B-Instruct or just 'llama'",
  "model.search.searching": "searching…",
  "model.search.loading": "Loading {id}…",
  "model.search.error": "Failed to load model",
  "model.search.offline": "Hugging Face unreachable — showing built-in models.",
  "model.badge.config": "live config.json",
  "model.badge.base": "base model config",
  "model.badge.bundled": "built-in DB",
  "model.badge.manual": "manual",
  "model.params": "{n} params",
  "model.heads": "heads",

  "field.params": "Params",
  "field.layers": "Layers",
  "field.hidden": "Hidden size",
  "field.attnHeads": "Attn heads",
  "field.kvHeads": "KV heads",
  "field.headDim": "Head dim",
  "common.optional": "optional",
  "common.gqa": "GQA",
  "common.mla": "MLA",
  // Shown under the KV cache figure when the model compresses its cache, so the
  // number is explained rather than merely different.
  "kv.mlaNote": "This model uses multi-head latent attention: it caches one compressed latent per token per layer ({d} values) instead of a key and value tensor per head, so the cache is far smaller than its head counts suggest.",

  "warning.gatedBundled": "Gated model — architecture loaded from the built-in database.",
  "warning.gatedUnknown":
    "Gated model and not in the built-in database — enter the architecture manually below.",
  "warning.configFailed":
    "Could not read this model's config — enter the architecture manually below.",
  "warning.archFromBase": "Architecture loaded from the base model (this repo has no config of its own).",

  "quality.wd.fp32": "Full precision. Twice the memory of BF16 for no practical inference gain — almost nobody serves at FP32.",
  "quality.wd.fp16": "The reference point. Every quality note below is relative to this.",
  "quality.wd.bf16": "The reference point. Every quality note below is relative to this.",
  "quality.wd.fp8": "Close to the reference on most tasks, but needs hardware support (Hopper / Ada and newer) and a checkpoint shipped or calibrated for FP8.",
  "quality.wd.int8": "Usually a small, task-dependent loss with weight-only quantization and a decent calibration set. Quantizing activations as well is where it gets risky.",
  "quality.wd.int4": "The biggest quality risk. A well-made AWQ / GPTQ checkpoint holds up on chat far better than naive round-to-nearest, but code, maths and long-context reasoning degrade first — validate on your own task before shipping.",
  "quality.kv.fp16": "Reference precision for the cache.",
  "quality.kv.bf16": "Reference precision for the cache.",
  "quality.kv.fp8": "Halves the cache. The accuracy cost grows with context length, so validate on long inputs rather than short ones.",
  "controls.step": "Precision & workload",
  "controls.weightQuant": "Weight quantization",
  "controls.kvPrecision": "KV cache precision",
  "controls.kvHint": "serving-side · FP8 halves KV",
  "controls.context": "Context window (tokens / sequence)",
  "controls.contextMax": "model max {n}",
  "controls.tok": "tok",
  "controls.users": "Concurrent users / requests",
  "controls.usersHint": "batch size held in cache",
  "controls.overhead": "Overhead (activations + fragmentation)",

  "results.title": "Estimated VRAM",
  "results.totalRequired": "total required",
  "seg.weights": "Weights",
  "seg.kv": "KV cache",
  "seg.act": "Activations",
  "seg.cuda": "CUDA/overhead",
  "stat.weights": "Weights",
  "stat.kvTotal": "KV cache (total)",
  "stat.kvSeq": "KV / sequence",
  "stat.kvToken": "KV / token",
  "stat.headDim": "head dim {n}",

  "gpu.step": "GPU fit",
  "gpu.pickPrompt": "Pick a GPU to check it against this model",
  "gpu.pickHint":
    "This model needs about {x}. Choose a card below and you get the fit verdict, how many concurrent users it holds, how much context it can carry and the expected decode speed.",
  "gpu.usableHint": "assumes {p}% of VRAM usable",
  "gpu.fits": "fits ✓",
  "gpu.needs": "needs {n}× GPUs",
  "gpu.usage": "{x} / {y} GB ({p}% of usable)",
  "gpu.maxUsers": "Max concurrent users",
  "gpu.atCtx": "at {x} ctx",
  "gpu.maxContext": "Max context / user",
  "gpu.atUsers": "at {n} concurrent",
  "gpu.tokens": "tokens",
  "gpu.weightsNoFit": "weights don't fit",
  "gpu.recTitle": "What would work",
  "gpu.recSmallest": "smallest device that fits",
  "gpu.recQuant": "keeps {gpu} — {x}",
  "gpu.recNone": "No single device in the database fits this configuration, and no lighter precision brings it under. Shorten the context, drop concurrency, or plan for tensor parallelism.",
  "gpu.recSmaller": "{name} ({mem} GB) would also fit.",
  "gpu.recSwitch": "Switch",
  "gpu.decodeSpeed": "Decode speed",
  "gpu.tpsSingle": "tok/s, one user",
  "gpu.tpsBatch": "tok/s per user · ~{total} total",
  "gpu.speedNote": "Bandwidth-bound estimate at {p}% of peak: each token reads the active weights plus the KV cache. Prefill (time to first token) is compute-bound and not included.",
  "gpu.mig": "MIG profile",
  "gpu.noFitSingle": "doesn't fit",
  "gpu.tpTitle": "{n}x GPUs means tensor parallelism",
  "gpu.tpHeadsOk": "{n} divides the {kv} KV heads, so vLLM accepts --tensor-parallel-size {n}.",
  "gpu.tpHeads": "The TP size has to divide the {kv} KV heads — use {ok} rather than this count.",
  "gpu.tpNvlink": "Consumer cards mostly have no NVLink or P2P, so sharding one model across them is slow.",
  "gpu.tpOverhead": "Memory does not divide evenly: activations and communication buffers are duplicated on every card.",
  "gpu.tpLink": "Open this setup on the vLLM page",
  "gpu.unifiedSingle": "A unified-memory device is a single box — you cannot add a second one to serve one model. Lower the precision, shorten the context, or pick a device with more memory.",
  "gpu.migOff": "Full GPU (no MIG)",
  "gpu.cardFits": "fits · {p}%",
  "gpu.cardNeeds": "{n}× needed",
  // Marks the selected card when it is shown among the fitting ones despite
  // being over budget — the group it sits in no longer implies it fits, so the
  // card has to state the verdict itself rather than only explain its presence.
  "gpu.cardOverBudget": "over budget",
  "gpu.unified": "{total} GB unified → ~{usable} GB usable · {bw} GB/s",
  "gpu.bw": "{bw} GB/s",
  "gpu.showNonFit": "Show non-fitting ({n})",
  "gpu.hideNonFit": "Hide non-fitting",
  "gpu.noneFit": "None in this tier fit this model",
  "cat.consumer": "Consumer",
  "cat.workstation": "Workstation",
  "cat.datacenter": "Data center",
  "cat.apple": "Apple",
  "cat.apu": "AI PC (unified)",

  "method.summary": "How the numbers are calculated",
  "method.weightsTerm": "Weights",
  "method.weightsText":
    "= parameters × bytes/param (FP16/BF16 = 2, FP8/INT8 = 1, INT4 = 0.5). For Mixture-of-Experts models, all experts are loaded, so total params are used — not the active subset.",
  "method.kvTerm": "KV cache",
  "method.kvText":
    "= 2 × layers × kv_heads × head_dim × bytes × context × concurrency. Grouped-Query Attention (kv_heads < attn_heads) shrinks this dramatically — it's read from each model's config. Multi-head latent attention (DeepSeek) caches layers × (kv_lora_rank + qk_rope_head_dim) × bytes per token instead.",
  "method.overheadTerm": "Overhead",
  "method.overheadText":
    "adds activations + fragmentation (a configurable %) plus a fixed CUDA context allowance. GPU fit assumes ~95% of nominal VRAM is usable.",
  "method.disclaimer":
    "Estimates are for planning, not a guarantee. Real usage varies by serving engine (vLLM, TGI, llama.cpp) and its paged-attention efficiency.",

  "footer.builtBy": "Built by",
  "footer.privacy": "Sizing runs in your browser — no account, no backend. Visits are counted anonymously, without cookies.",
  "link.github": "GitHub",
  "link.linkedin": "LinkedIn",
  "link.hf": "Hugging Face",

  "nav.sizing": "VRAM Sizing",
  "nav.fit": "Task Fit",

  "fit.title": "Model ↔ Task Fit",
  "fit.subtitle":
    "Is this model built for the job? Pick a model and your use-case — LLMScale matches the characteristics the model declares (size, context, tuning, modality) against what the task needs, and shows every criterion it used.",
  "fit.pickTask": "Choose your task",
  "fit.scoreLabel": "Capability match",
  "fit.empty": "Pick a model and a task to check the fit.",
  "fit.scoreUnit": "of the criteria checked",
  "fit.methodNote": "Read from what the model declares — size, context, tuning, modality. It cannot see answer quality, grounding or hallucination rate, so a high match means \u201Cbuilt for this\u201D, not \u201Cgood at this\u201D. Only your own evaluation settles that.",
  "fit.criteriaTitle": "Why this score",

  "fit.verdict.great": "Built for this",
  "fit.verdict.good": "Workable",
  "fit.verdict.weak": "Thin on paper",
  "fit.verdict.poor": "Wrong tool",

  "fit.task.chat": "Chatbot / assistant",
  "fit.task.code": "Code generation",
  "fit.task.rag": "RAG / doc Q&A",
  "fit.task.summarize": "Long-doc summarize",
  "fit.task.agent": "Agents / tool use",
  "fit.task.reasoning": "Reasoning & math",
  "fit.task.multilingual": "Multilingual",
  "fit.task.vision": "Vision / multimodal",
  "fit.task.embeddings": "Embeddings / search",
  "fit.task.edge": "On-device / edge",
  "fit.task.throughput": "High-throughput serving",

  "fit.crit.modality": "Model type",
  "fit.crit.instruct": "Instruction tuning",
  "fit.crit.size": "Model size",
  "fit.crit.context": "Context window",
  "fit.crit.code": "Code ability",
  "fit.crit.reasoning": "Reasoning",
  "fit.crit.multilingual": "Multilingual",
  "fit.crit.efficiency": "Serving efficiency",

  "fit.msg.modalityGen": "Generative text model",
  "fit.msg.modalityEmbedding": "This is an embedding model — not built for generation",
  "fit.msg.modalityReranker": "This is a reranker/classifier — not built for generation",
  "fit.msg.modalityUnknownGen": "Couldn't confirm this is a generative model",
  "fit.msg.instructYes": "Chat / instruction-tuned",
  "fit.msg.instructBase": "Base model — prefer an -Instruct variant",
  "fit.msg.instructUnknown": "Instruction tuning unclear",
  "fit.msg.size": "{params} (recommended ≥ {ideal}B)",
  "fit.msg.context": "{ctx} tokens (recommended ≥ {ideal}k)",
  "fit.msg.contextUnknown": "Context length unknown",
  "fit.msg.codeYes": "Code-specialized",
  "fit.msg.codeNo": "Not code-specialized",
  "fit.msg.reasonYes": "Reasoning / math-tuned",
  "fit.msg.reasonNo": "Not reasoning-tuned — leans on raw scale",
  "fit.msg.multiYes": "Multilingual",
  "fit.msg.multiNo": "Looks English-centric",
  "fit.msg.visionYes": "Multimodal (vision) model",
  "fit.msg.visionNo": "No vision capability — pick a -VL / multimodal model",
  "fit.msg.embedYes": "Embedding model",
  "fit.msg.embedNo": "Not an embedding model — use e.g. BGE, E5, Qwen3-Embedding",
  "fit.msg.edgeSize": "{params} — smaller runs better on device",
  "fit.msg.effMoE": "MoE — low active compute, strong throughput",
  "fit.msg.effDense": "{params} dense — heavier compute per token",

  "nav.vllm": "vLLM Params",
  "nav.decode": "Name Decoder",
  "nav.anatomy": "Model Anatomy",
  "nav.compare": "Model Compare",
  "nav.train": "Fine-tune",
  "train.subtitle":
    "What does fine-tuning cost in GPU memory? Training drops the KV cache but adds gradients, optimizer state and the activations kept for the backward pass — which is why a model you can serve on one card often cannot be trained on it.",
  "train.setup": "Training setup",
  "train.mode": "Method",
  "train.mode.full": "Full",
  "train.modeNote.full": "Every parameter is trained: 16 bytes each for weights, gradients and Adam state. The heaviest option by a wide margin.",
  "train.modeNote.lora": "The base is frozen in bf16 and only a small adapter is trained, so gradients and optimizer state nearly vanish. Activations do not.",
  "train.modeNote.qlora": "As LoRA, but the frozen base is held in 4-bit — roughly a quarter of the resident weights, at some quality cost on the base.",
  "train.rank": "LoRA rank",
  "train.target": "Adapter on",
  "train.target.attn": "Attention",
  "train.target.all": "All linear",
  "train.batch": "Batch size (per device)",
  "train.seq": "Sequence length",
  "train.ckpt": "Gradient checkpointing",
  "train.ckptHint": "recompute instead of storing",
  "train.on": "On",
  "train.off": "Off",
  "train.results": "Memory needed",
  "train.totalRequired": "per device",
  "train.seg.base": "Base weights",
  "train.seg.grads": "Gradients",
  "train.seg.optim": "Optimizer",
  "train.seg.act": "Activations",
  "train.seg.overhead": "Overhead",
  "train.noteFull": "Optimizer state dominates: Adam keeps an fp32 master copy plus two moments, three times the size of the bf16 weights themselves.",
  "train.noteAdapter": "Freezing the base removes almost all gradient and optimizer memory, but the backward pass still runs through every layer — so activations cost the same as a full fine-tune. Checkpointing, batch size and sequence length are the levers left.",
  "train.gpuFit": "Which GPUs fit",
  "train.shardNote": "Unlike serving, sharding is the norm here: FSDP or DeepSpeed ZeRO-3 splits parameters, gradients and optimizer state across the ranks, so this total divides close to linearly. Activations do not shrink — cut batch size or sequence length for those.",
  "train.method": "Mixed-precision Adam at 16 bytes/parameter (bf16 weights + bf16 gradients + fp32 master, m and v). Activations follow Korthikanti et al. 2022 at ~34 bytes per token per layer per hidden unit, flash-attention assumed, or 2 bytes with full recomputation. Real runs vary with framework and kernel choices; treat this as a planning figure.",
  "theme.dark": "Dark",
  "theme.light": "Light",
  "theme.glass": "Glass",
  // One h1 per surface, visually hidden. Names the page for a screen reader and
  // for a crawler; the visible design opens straight into its first card.
  "h1.sizing": "LLM VRAM calculator — model weights, KV cache and GPU fit",
  "h1.train": "Fine-tuning VRAM — LoRA, QLoRA and full fine-tune memory",
  "h1.fit": "Task fit — is this LLM right for the job?",
  "h1.anatomy": "Model anatomy — where an LLM's parameters and memory go",
  "h1.compare": "Compare LLMs side by side",
  "h1.decode": "LLM model name decoder",
  "h1.vllm": "vLLM parameter helper — a tuned vllm serve command",
  "h1.learn": "LLM 101 — how a language model works",
  "nav.learn": "LLM 101",
  "compare.subtitle":
    "Put 2–4 models side by side — specs, capabilities and per-task fit — to see which one is better for which use, from live Hugging Face data.",
  "compare.pickTitle": "Models",
  "compare.count": "{n} / {max}",
  "compare.search": "+ Add a model…",
  "compare.max": "Max 4 models",
  "compare.empty": "Add models to compare.",
  "compare.loadingCol": "loading…",
  "compare.err": "not found",
  "compare.remove": "Remove",
  "compare.dense": "dense",
  "compare.sec.identity": "Identity & popularity",
  "compare.sec.arch": "Architecture & memory",
  "compare.sec.caps": "Capabilities",
  "compare.sec.fit": "Task fit",
  "compare.fitHint": "score 0–100 · best highlighted",
  "compare.row.params": "Parameters",
  "compare.row.moe": "MoE (active / total)",
  "compare.row.context": "Context",
  "compare.row.license": "License",
  "compare.row.downloads": "Downloads (30d)",
  "compare.row.likes": "Likes",
  "compare.row.updated": "Updated",
  "compare.row.base": "Base model",
  "compare.row.precision": "Precision",
  "compare.row.layers": "Layers",
  "compare.row.hidden": "Hidden size",
  "compare.row.heads": "Attn / KV heads",
  "compare.row.headDim": "Head dim",
  "compare.row.vocab": "Vocab",
  "compare.row.weights": "Weights (native)",
  "compare.row.kvtoken": "KV / token",
  "compare.row.vram8k": "VRAM @ 8k · 1 user",
  "compare.cap.instruct": "Instruction-tuned",
  "compare.cap.code": "Code",
  "compare.cap.math": "Math",
  "compare.cap.reasoning": "Reasoning",
  "compare.cap.vision": "Vision",
  "compare.cap.multilingual": "Multilingual",
  "compare.cap.embedding": "Embeddings",
  "compare.tip.params": "Total parameters. More = more capable/knowledgeable, but heavier — more VRAM, slower, costlier to run.",
  "compare.tip.moe": "MoE active / total experts. All experts must fit in VRAM (total), but only a few run per token (active) — big capacity at fast compute.",
  "compare.tip.context": "Max tokens the model can attend to. Longer = handles bigger docs / RAG, but KV cache grows → more VRAM.",
  "compare.tip.license": "Usage license. Permissive (Apache/MIT) = fewer restrictions; some licenses limit commercial or gated use.",
  "compare.tip.downloads": "30-day downloads — an adoption/popularity signal, not quality. More = wider community use & support.",
  "compare.tip.likes": "Hub likes — a community-interest signal, not a quality measure.",
  "compare.tip.updated": "Last-modified date. More recent = likelier fixes/improvements, though very new can be less battle-tested.",
  "compare.tip.base": "The model this was fine-tuned / quantized from. Shows lineage; capabilities are largely inherited from it.",
  "compare.tip.precision": "Native weight format. Lower bits (INT4/FP8) = smaller & faster, with a slight accuracy trade-off vs BF16/FP16.",
  "compare.tip.layers": "Transformer blocks (depth). More = more capacity, but higher latency and more KV cache per token.",
  "compare.tip.hidden": "Hidden dimension (width). Larger = more representational power, but more parameters & memory.",
  "compare.tip.heads": "Attention / KV heads. Fewer KV heads (GQA) = a much smaller KV cache with minimal quality loss.",
  "compare.tip.headDim": "Dimension per attention head. A larger head_dim raises KV cache size per token.",
  "compare.tip.vocab": "Tokenizer vocabulary size. Larger = better multilingual coverage, but a bigger embedding matrix.",
  "compare.tip.weights": "Weight memory at native precision. Smaller = fits smaller GPUs; larger models are usually more capable.",
  "compare.tip.kvtoken": "KV cache per token (FP16). Smaller = more concurrent users / longer context per GPU (GQA helps).",
  "compare.tip.vram8k": "Estimated total VRAM at 8k context, 1 user. Lower = cheaper to serve / fits smaller GPUs.",
  "compare.tip.capGeneric": "✓ = the model is tuned/suited for {cap}; ✗ = not specialized for it.",
  "compare.tip.taskGeneric": "Suitability for {task} (0–100). Higher = better fit; the best model in the row is highlighted.",
  "anatomy.subtitle":
    "A visual X-ray of the model: where its parameters live, how it's quantized, its attention shape and how KV cache grows — all from live Hugging Face data.",
  "anatomy.loading": "Loading model anatomy…",
  "anatomy.empty": "Pick a model to see its anatomy.",
  "anatomy.disclaimer":
    "Parameter split is derived from the config — embeddings + attention are exact; the feed-forward / expert block is the remainder. Estimates for guidance.",
  "anatomy.params.title": "Parameter distribution",
  "anatomy.params.embeddings": "Embeddings",
  "anatomy.params.attention": "Attention",
  "anatomy.params.mlp": "Feed-forward (MLP)",
  "anatomy.params.experts": "Experts (MoE)",
  "anatomy.params.totalSub": "total params",
  "anatomy.params.activeNote":
    "MoE: only ~{active} params ({perTok} of {experts} experts) are active per token — but all of them must fit in VRAM.",
  "anatomy.precision.title": "Precision & memory",
  "anatomy.precision.mix": "As-shipped precision mix",
  "anatomy.precision.mixNA": "Precision mix unavailable for this repo (gated, or no safetensors index).",
  "anatomy.precision.native": "native",
  "anatomy.precision.memTitle": "Weights if fully at…",
  "anatomy.arch.title": "Architecture",
  "anatomy.arch.layers": "Layers",
  "anatomy.arch.hidden": "Hidden size",
  "anatomy.arch.headDim": "Head dim",
  "anatomy.arch.heads": "Attn / KV heads",
  "anatomy.arch.mlpRatio": "MLP expansion",
  "anatomy.arch.context": "Context",
  "anatomy.arch.vocab": "Vocab",
  "anatomy.arch.experts": "Experts (act / total)",
  "anatomy.arch.expertsSub": "per token / total",
  "anatomy.arch.gqaTitle": "Attention grouping",
  "anatomy.arch.gqaNote": "GQA: {q} query heads share {kv} KV heads ({ratio}:1) — cuts KV cache ~{ratio}×.",
  "anatomy.arch.mhaNote": "MHA: {n} query heads, each with its own KV head (no GQA sharing).",
  "anatomy.arch.hint": "how a token flows through the model",
  "anatomy.diagram.input": "Tokenized input",
  "anatomy.diagram.embed": "Token embedding",
  "anatomy.diagram.attn": "Grouped-query attention",
  "anatomy.diagram.attnMha": "Multi-head attention",
  "anatomy.diagram.mlp": "Feed-forward · SwiGLU",
  "anatomy.diagram.moe": "Mixture-of-Experts",
  "anatomy.diagram.finalNorm": "Final norm",
  "anatomy.diagram.output": "Output projection",
  "anatomy.diagram.block": "Transformer block",
  "anatomy.diagram.blockN": "× {n}",
  "anatomy.diagram.expertsDetail": "{act}/{tot} experts",
  "anatomy.diagram.activeSub": "active params",
  "anatomy.diagram.totalSub": "total params",
  "anatomy.diagram.flow": "Data flows bottom → top · one token's path",
  "anatomy.diagram.expertsLabel": "active / total experts",
  "anatomy.diagram.moeLabel": "mixture of experts",
  "anatomy.diagram.swigluLabel": "SwiGLU intermediate",
  "anatomy.diagram.logitsLabel": "output logits",
  "anatomy.diagram.headDimLabel": "head dim",
  "anatomy.diagram.vocabLabel": "vocab size",
  "anatomy.diagram.dimLabel": "embedding dim",
  "anatomy.kv.title": "KV cache growth",
  "anatomy.kv.gqaLegend": "This model",
  "anatomy.kv.mhaLegend": "Without GQA (MHA)",
  "anatomy.kv.noteGqa": "GQA keeps KV cache ~{ratio}× smaller than plain multi-head attention.",
  "anatomy.kv.noteMha": "KV cache per sequence (FP16) as context grows.",
  "anatomy.meta.downloads": "Downloads (30d)",
  "anatomy.meta.likes": "Likes",
  "anatomy.meta.license": "License",
  "anatomy.meta.updated": "Updated",
  "anatomy.meta.size": "Repo size",
  "anatomy.meta.base": "Fine-tuned / quantized from",
  "decode.subtitle":
    "What does each part of a model name mean? Type or pick a model — every token (size, quantization, variant…) is colour-coded and explained. Hover to highlight.",
  "decode.input": "Model name",
  "decode.breakdown": "Breakdown",
  "decode.hint": "Hover a token to light up its meaning.",
  "decode.empty": "Type a model name to decode it.",
  "vllm.subtitle":
    "Generate a tuned `vllm serve` command. Pick a model, what you're optimizing for, and your workload — LLMScale recommends flags for the best performance, accuracy and reliability, with a copyable command.",
  "vllm.pickPriority": "Optimize for",
  "vllm.pickTask": "Workload",
  "vllm.noMetal": "{gpu} cannot serve with vLLM — there is no Metal backend. Switched to H100 80GB; the memory maths for it is still on the sizing page.",
  "vllm.gpuCount": "GPU count",
  "vllm.maxlen": "Max context (max-model-len)",
  "vllm.commandTitle": "Recommended command",
  "vllm.copy": "Copy",
  "vllm.copied": "Copied ✓",
  "vllm.copyK8s": "K8s args",
  "vllm.k8sHint": "Copy as Kubernetes args: one --key=value per line, no serve/model.",
  "vllm.model": "model",
  "vllm.flagsTitle": "What each flag does",
  "vllm.warningsTitle": "Notes & warnings",
  "vllm.empty": "Pick a model to generate vLLM parameters.",

  "vllm.prio.balanced": "Balanced",
  "vllm.prio.throughput": "Throughput",
  "vllm.prio.latency": "Low latency",
  "vllm.prio.accuracy": "Max accuracy",
  "vllm.prio.memory": "Memory-tight",

  "vllm.task.chat": "Chat / assistant",
  "vllm.task.rag": "RAG / long context",
  "vllm.task.code": "Code",
  "vllm.task.tool": "Tool use / agents",
  "vllm.task.structured": "Structured JSON",
  "vllm.task.vision": "Vision / multimodal",
  "vllm.task.reasoning": "Reasoning",

  "vllm.r.maxlen": "Caps the context window — frees KV cache vs the model's full max.",
  "vllm.r.tp": "Shards the model across GPUs (tensor parallelism).",
  "vllm.r.ep": "Expert parallelism for MoE layers across GPUs.",
  "vllm.r.gpuutil": "Share of VRAM vLLM may use for weights + KV cache.",
  "vllm.r.kvfp8": "FP8 KV cache ~halves cache memory — fits more / longer sequences.",
  "vllm.r.maxbatched": "Large prefill batch maximizes throughput.",
  "vllm.r.maxbatchedLat": "Smaller prefill batch lowers inter-token latency.",
  "vllm.r.maxseqs": "Allow many concurrent sequences for throughput.",
  "vllm.r.maxseqsLat": "Fewer concurrent sequences keeps latency low.",
  "vllm.r.maxseqsMem": "Cap concurrency to limit KV cache memory.",
  "vllm.r.chunked": "Chunked prefill stops long prompts from stalling decode.",
  "vllm.r.prefix": "Prefix caching reuses shared system / context prefixes.",
  "vllm.r.tool": "Enables automatic tool / function calling.",
  "vllm.r.toolparser": "Parser matching this model family ({parser}).",
  "vllm.r.guided": "xgrammar backend for fast, reliable JSON / grammar output.",
  "vllm.r.mm": "Limit images per prompt for multimodal input.",
  "vllm.r.dtype": "Full BF16 weights for best accuracy.",
  "vllm.r.seed": "Fixed seed for reproducible, reliable outputs.",

  "vllm.w.ctxcap": "Requested context exceeds the model max ({max}) — vLLM will reject it or need rope scaling.",
  "vllm.w.fp8acc": "FP8 KV cache can hurt accuracy on long-context tasks — validate before production.",
  "vllm.w.kvfull": "KV cache kept in full precision (auto) for maximum accuracy.",
  "vllm.w.template": "This parser usually needs a model-specific --chat-template (see vLLM examples/).",
  "vllm.w.parserUnknown": "Couldn't detect the tool-call parser — set --tool-call-parser to match your model.",
  "vllm.w.trust": "Many multimodal models also need --trust-remote-code.",
  "vllm.w.quant": "Pre-quantized model ({q}) — vLLM auto-detects it; no --quantization needed.",
  "vllm.w.gguf": "GGUF support in vLLM is experimental — a safetensors/native repo is recommended.",
  "vllm.w.seqcap": "--max-num-seqs capped at {fit}: that is all the KV cache holds at {ctx} tokens. Raising it only lengthens the queue.",
  "vllm.w.fit": "~{need} GiB needed vs ~{have} GiB available — add GPUs (≈{gpus}), quantize, shorten context, or use FP8 KV.",
  "vllm.w.mig": "MIG = one isolated GPU slice; tensor-parallel across MIG isn't supported. Pin the instance with CUDA_VISIBLE_DEVICES=MIG-…",

  // Visible explainer under each tool (components/About.tsx). Every figure is one the engine produces or a published result it is tested against.
  "about.faq": "Questions",
  "about.sizing.title": "What this calculator assumes",
  "about.sizing.p1": "LLMScale reads each model's architecture from its config.json on the Hugging Face Hub — layers, attention and key-value heads, head size — and sizes GPU memory from that, not from the parameter count alone. Gated models such as Llama, Gemma and Mistral, whose config a browser cannot read, come from a bundled database; a repository without a config of its own, such as a GGUF fork, is resolved through its base_model.",
  "about.sizing.p2": "Every card is budgeted at 95% of its nominal memory. Unified-memory devices use a realistic share instead of the whole pool: 75% of an Apple Mac's memory, 96 of 128 GB on Strix Halo, 120 of 128 GB on DGX Spark. Decode speed is estimated from memory bandwidth at 80% efficiency; prompt processing (prefill) is not modelled. The figures are for capacity planning — the serving engine and its paged-attention efficiency still move the real number.",
  "about.sizing.q1": "How much VRAM does a 70B model need?",
  "about.sizing.a1": "The weights alone take about 130 GiB at BF16, 65 GiB at FP8 and 33 GiB at INT4 (70 billion parameters × 2, 1 or 0.5 bytes). The KV cache and overhead come on top, and both depend on the context window and the number of users — which is what the calculator works out.",
  "about.sizing.q2": "Why does the context window change the answer so much?",
  "about.sizing.a2": "The KV cache grows linearly with context length and with concurrent users. Llama 3.1 8B stores 131,072 bytes per token at FP16: 1 GiB for one user at 8k tokens, 16 GiB at 128k — and 16 GiB again at 8k with 16 users.",
  "about.sizing.q3": "Does a Mixture-of-Experts model need less memory?",
  "about.sizing.a3": "Not for memory. Every expert has to be loaded, so memory is sized from the total parameter count. Only some of the experts run for each token, which is why MoE models generate faster than their size suggests.",
  "about.sizing.q4": "How is DeepSeek's KV cache handled?",
  "about.sizing.a4": "DeepSeek-V2 and V3 use multi-head latent attention (MLA), which caches one compressed latent per layer instead of keys and values for every head. The calculator reads kv_lora_rank and qk_rope_head_dim from the config and uses layers × (kv_lora_rank + qk_rope_head_dim) × bytes per token. For DeepSeek-V3 at 8k context that is 0.54 GiB, where the usual formula would give 13.34 GiB.",
  "about.train.title": "How fine-tuning memory is worked out",
  "about.train.p1": "Fine-tuning holds more than the weights. Every trainable parameter also needs a gradient and optimizer state, and the forward pass keeps activations for the backward pass. LoRA and QLoRA freeze the base model and train small adapters, so gradients and optimizer state shrink to the adapters' size; QLoRA also stores the frozen base in 4-bit NF4.",
  "about.train.f1": "base weights = parameters × 2 bytes (BF16), or × 0.516 bytes (QLoRA NF4)",
  "about.train.f2": "gradients = trainable parameters × 2 bytes",
  "about.train.f3": "optimizer (Adam) = trainable parameters × 12 bytes: FP32 master weights + two moments",
  "about.train.f4": "activations = layers × sequence length × batch × hidden size × 34 bytes, or × 2 with gradient checkpointing",
  "about.train.f5": "total = base + gradients + optimizer + activations + 1 GiB overhead",
  "about.train.p2": "A full fine-tune trains every parameter; for LoRA the count follows from the rank and the target modules — the attention projections, or every linear layer. Activations assume flash attention. The engine is checked against two published results: the ZeRO paper's 16 bytes per parameter for mixed-precision Adam, and QLoRA fine-tuning a 65B model on one 48 GB card, which it puts at 43.3 GiB.",
  "about.train.q1": "How much VRAM does a full fine-tune need?",
  "about.train.a1": "About 16 bytes per parameter before activations: 2 for the weights, 2 for gradients and 12 for Adam. That is roughly 104 GiB for a 7B model, which is why a full fine-tune usually means several GPUs, or sharding with ZeRO-3 or FSDP.",
  "about.train.q2": "LoRA or QLoRA — what is the memory difference?",
  "about.train.a2": "Both train the same adapters; the difference is the frozen base. LoRA keeps it at BF16 (2 bytes per parameter), QLoRA at NF4 (0.516 bytes). For an 8B model that is about 14.9 GiB against 3.8 GiB for the base weights alone.",
  "about.train.q3": "Does LoRA reduce activation memory?",
  "about.train.a3": "No. The forward pass still runs through the whole model, so activations are the same as in a full fine-tune. Gradient checkpointing is what cuts them: it keeps only each layer's input — 2 bytes instead of 34 per layer, token and hidden unit — and recomputes the rest.",
  "about.train.q4": "Why is there no KV cache here?",
  "about.train.a4": "Training processes whole sequences in one pass and does not cache keys and values between steps the way text generation does, so the KV cache term from the inference calculator does not apply.",
  "about.fit.title": "How the fit score works",
  "about.fit.p1": "The score is rule-based and transparent. It reads what the Hugging Face Hub says about a model — its tags, pipeline tag, repository name and model type — with its parameter count and maximum context, and checks those signals against what each task needs: instruction tuning, code or reasoning training, vision, multilingual data, enough context, a suitable size.",
  "about.fit.p2": "Each of the 11 tasks weighs its criteria differently: RAG leans on context (32k tokens is ideal), on-device use on a small size. The overall score is the weighted mean out of 100, and a hard mismatch — an embedding model asked to chat, a text-only model asked to see — caps it at 25. From 80 a model is “built for this”, from 60 “workable”, from 40 “thin on paper”, and below that “the wrong tool”.",
  "about.fit.q1": "Which tasks are scored?",
  "about.fit.a1": "Chatbot and assistant, code generation, RAG and document Q&A, long-document summarisation, agents and tool use, reasoning and math, multilingual, vision and multimodal, embeddings and search, on-device and edge, and high-throughput serving.",
  "about.fit.q2": "Does a high score mean the model is good?",
  "about.fit.a2": "It means the model is built for the task, not that it is good at it. The score cannot see answer quality, grounding or hallucination rate — benchmarks and your own evaluation still decide between two models that both fit.",
  "about.fit.q3": "Why does an instruct model score higher for chat?",
  "about.fit.a3": "Base models are not trained to follow instructions, so the chat task gives instruction tuning its largest weight, 45%. The page detects it from tags such as conversational or chat, and from names containing Instruct, Chat or -it.",
  "about.fit.q4": "Can a capable model score lower than it deserves?",
  "about.fit.a4": "Yes. The rules only see what a model declares, so a model with sparse tags or a terse name loses points on signals it never states. Check the criteria list: each one shows what was found and what it was worth.",
  "about.anatomy.title": "What the anatomy shows",
  "about.anatomy.p1": "The anatomy view splits a model's parameters by where they live. Embeddings are the vocabulary table — counted twice when input and output embeddings are not tied. Attention is the query, key, value and output projections. Everything else, mostly the feed-forward network or the experts, is the remainder, so the parts always add up to the model's real total.",
  "about.anatomy.f1": "embeddings = vocabulary × hidden size (× 2 if untied)",
  "about.anatomy.f2": "attention = 2 × layers × hidden size × head_dim × (attention heads + key-value heads)",
  "about.anatomy.f3": "feed-forward / experts = total parameters − embeddings − attention",
  "about.anatomy.f4": "active experts (MoE) = feed-forward × experts per token ÷ experts",
  "about.anatomy.p2": "The KV cache chart plots one sequence at FP16 from zero to the model's maximum context, up to 128k tokens. For a model with grouped-query attention a dashed line shows what full multi-head attention would have cost — the gap is what GQA saves. The precision card shows what the weights weigh at BF16, FP8 or INT8, and INT4.",
  "about.anatomy.q1": "What is grouped-query attention (GQA)?",
  "about.anatomy.a1": "Several query heads share one set of key and value heads. The KV cache grows with the number of key-value heads, not query heads, so a model with 64 query heads and 8 key-value heads caches 8 times less than full multi-head attention would.",
  "about.anatomy.q2": "Why do embeddings take such a large share of small models?",
  "about.anatomy.a2": "The embedding table is vocabulary × hidden size, and modern vocabularies are large. In Qwen2.5 7B the embeddings hold about 1.09 billion parameters against 0.82 billion in attention; the feed-forward layers take most of the rest.",
  "about.anatomy.q3": "Why does a MoE model show far fewer active parameters?",
  "about.anatomy.a3": "Only a few experts run for each token. The active figure counts the embeddings, the attention and the share of expert parameters a token actually passes through — memory still has to hold all of them.",
  "about.anatomy.q4": "Where does the data come from?",
  "about.anatomy.a4": "From the model's config.json and the Hugging Face model API, fetched live in your browser. Downloads, likes, licence and repository size come from the same place.",
  "about.compare.title": "What the comparison measures",
  "about.compare.p1": "Put two to four models from the Hugging Face Hub side by side. Each column is resolved the same way as on the other pages: parameters, experts, maximum context, licence, downloads, likes, last update and base model; the precision the weights ship in and what they weigh; the KV cache per token at FP16; and the GPU memory needed for 8k tokens and one user.",
  "about.compare.p2": "Below that come the capabilities the Hub declares — instruct, code, math, reasoning, vision, multilingual, embedding — and the task-fit score for all 11 tasks. The best value is highlighted for context, downloads, likes and each task score; a row where every model ties stays plain.",
  "about.compare.q1": "Is the VRAM figure the same as the calculator's?",
  "about.compare.a1": "It comes from the same engine at a fixed workload: 8k context, one user, FP16 KV cache, 10% overhead and 0.75 GiB of CUDA context. Open the model in the VRAM calculator to size it for your own context and number of users.",
  "about.compare.q2": "Why does a quantized model sometimes show BF16?",
  "about.compare.a2": "When the precision cannot be detected from the quantization config, the repository name, torch_dtype or the safetensors header, the comparison assumes BF16. If the weight size looks too large, check the repository.",
  "about.compare.q3": "Which model is better for my task?",
  "about.compare.a3": "The task rows score how well each model is built for it — instruction tuning, context, size, declared capabilities. They cannot measure answer quality, so use them to shortlist, then try the finalists on your own prompts.",
  "about.compare.q4": "How many models can I compare?",
  "about.compare.a4": "Up to four at once. The selection lives in the page address, so a link opens the same comparison for someone else.",
  "about.decode.title": "How a model name is read",
  "about.decode.p1": "An open-weight model's name packs several independent decisions into one string: the family and version, the size, the architecture, what it was tuned for, and how it was quantized or packaged. The decoder takes the organisation from before the slash, splits the rest on hyphens and underscores, and matches each part against rules for those categories, in order.",
  "about.decode.p2": "It recognises parameter counts (8B, 350M), Mixture-of-Experts sizes (8x7B) and active parameters (A3B); quantization and formats (AWQ, GPTQ, GGUF and its Q levels, FP8, NVFP4 and MXFP4, BF16, W4A16, INT4, bitsandbytes 4-bit); tuning (Instruct, Chat, Base, Coder, Math, VL, Embedding, Reranker, and reasoning names such as R1, QwQ and Thinking); training methods (DPO, ORPO, GRPO, LoRA); context lengths (32k), dates and versions. It reads the name only — conventions differ between families, and a name can be wrong about its own contents.",
  "about.decode.q1": "What does A3B mean in a model name?",
  "about.decode.a1": "About 3 billion active parameters per token in a Mixture-of-Experts model. Qwen3-30B-A3B holds 30 billion parameters but sends each token through experts totalling around 3 billion: memory is needed for all 30B, while the compute per token is closer to a 3B model's.",
  "about.decode.q2": "What is the difference between GGUF, AWQ and GPTQ?",
  "about.decode.a2": "GGUF is a file format for llama.cpp and the tools built on it, usually carrying quantization levels such as Q4 or Q8 for CPUs, Apple Silicon and consumer GPUs. AWQ and GPTQ are 4-bit weight quantization methods stored as safetensors and aimed at GPU serving engines such as vLLM.",
  "about.decode.q3": "What do FP8, NVFP4 and MXFP4 mean?",
  "about.decode.a3": "Floating-point weight formats smaller than BF16. FP8 stores each weight in one byte, half of BF16; NVFP4 and MXFP4 are 4-bit formats, half a byte per weight, used on recent NVIDIA hardware and by models such as gpt-oss.",
  "about.decode.q4": "What is the difference between Instruct and Base?",
  "about.decode.a4": "A base model is only pretrained to continue text. An Instruct model — also named Chat or -it — has been further tuned to follow instructions and hold a conversation, which is what most applications want.",
  "about.vllm.title": "How the vllm serve flags are chosen",
  "about.vllm.p1": "Pick a model, a GPU and how many of them, a context length, a priority (balanced, throughput, low latency, max accuracy or memory-tight) and a task (chat, RAG, code, tool use, structured JSON, vision or reasoning). The helper turns that into a vllm serve command with a one-line reason for every flag, and the same flags as Kubernetes args.",
  "about.vllm.f1": "--max-model-len = the context you set",
  "about.vllm.f2": "--tensor-parallel-size = number of GPUs, plus --enable-expert-parallel for MoE models",
  "about.vllm.f3": "--gpu-memory-utilization = 0.95 for throughput or memory-tight, 0.90 otherwise",
  "about.vllm.f4": "--kv-cache-dtype fp8 = memory-tight or throughput priority, with 32k+ context or a RAG task",
  "about.vllm.f5": "--max-num-seqs = 512 (throughput), 32 (low latency) or 64 (memory-tight), capped at ⌊((GPUs × VRAM × utilization − 1 GiB) ÷ 1.1 − weights) ÷ KV per sequence⌋",
  "about.vllm.f6": "--enable-prefix-caching for chat, RAG, tool use and reasoning; --enable-chunked-prefill for long context",
  "about.vllm.p2": "Tool use adds --enable-auto-tool-choice with the tool-call parser for the model's family, structured JSON adds the xgrammar backend, and vision limits images per prompt. Pre-quantized repositories (AWQ, GPTQ, FP8, NVFP4) need no --quantization flag, and the page says so. A memory check — weights plus one full-length sequence of KV cache, × 1.1, + 1 GiB — warns when the model will not fit; it is coarser than the VRAM calculator, so use that for exact sizing. Apple devices are left out because vLLM has no Metal backend.",
  "about.vllm.q1": "What does --gpu-memory-utilization do?",
  "about.vllm.a1": "It is the fraction of each GPU's memory vLLM may take for model weights, activations and KV cache. What the weights do not use becomes KV cache, so a higher value fits more concurrent sequences and leaves less headroom for anything else on the card.",
  "about.vllm.q2": "Why is --max-num-seqs lower than I expected?",
  "about.vllm.a2": "The helper caps it at what the KV cache can actually hold at the context length you chose. Setting it higher does not add capacity: requests past that point wait in the queue.",
  "about.vllm.q3": "Should I use an FP8 KV cache?",
  "about.vllm.a3": "It halves the KV cache, so roughly twice as many sequences fit, but it can cost accuracy on long-context work. That is why the helper only suggests it when memory or throughput is the priority and the context is long, and asks you to validate it first.",
  "about.vllm.q4": "How many GPUs do I need for tensor parallelism?",
  "about.vllm.a4": "Enough for the weights and your workload's KV cache to fit. The memory check here estimates how many; the VRAM calculator shows the exact figure per card and suggests a GPU count that splits the model's key-value heads evenly.",
};

const tr: Dict = {
  "header.badge": "canlı Hugging Face verisi",
  "header.subtitle":
    "Bir model gerçekte ne kadar GPU belleği ister? Ağırlıklar ve KV cache, {ctx} ve {users} ile birlikte ölçeklenir. Bir model seç, yükü ayarla ve hangi GPU'ların yettiğini gör.",
  "header.subtitle.ctx": "context penceresi",
  "header.subtitle.users": "eşzamanlı kullanıcı",
  "header.share": "Bu tahmini paylaş",
  "header.shareCopied": "Link kopyalandı ✓",
  "results.empty": "VRAM kırılımını görmek için bir model seç.",
  "results.emptyHint":
    "Ağırlıklar, KV cache ve ek yük modelin kendi config'inden, tarayıcının içinde hesaplanır — yukarıdan Hugging Face'te ara ya da hazır bir modelle başla.",

  "model.step": "Model seç",
  "model.tab.search": "Hugging Face'te ara",
  "model.tab.presets": "Hazır modeller",
  "model.tab.custom": "Manuel",
  "model.search.placeholder": "ör. Qwen/Qwen2.5-7B-Instruct ya da sadece 'llama'",
  "model.search.searching": "aranıyor…",
  "model.search.loading": "{id} yükleniyor…",
  "model.search.error": "Model yüklenemedi",
  "model.search.offline": "Hugging Face'e ulaşılamadı — gömülü modeller gösteriliyor.",
  "model.badge.config": "canlı config.json",
  "model.badge.base": "base model config",
  "model.badge.bundled": "gömülü DB",
  "model.badge.manual": "manuel",
  "model.params": "{n} parametre",
  "model.heads": "head",

  "field.params": "Parametre",
  "field.layers": "Katman",
  "field.hidden": "Hidden size",
  "field.attnHeads": "Attn head",
  "field.kvHeads": "KV head",
  "field.headDim": "Head dim",
  "common.optional": "opsiyonel",
  "common.gqa": "GQA",
  "common.mla": "MLA",
  "kv.mlaNote": "Bu model multi-head latent attention kullanıyor: her head için ayrı key ve value tensörü yerine, katman ve token başına tek bir sıkıştırılmış latent ({d} değer) tutuyor — yani cache, head sayılarının ima ettiğinden çok daha küçük.",

  "warning.gatedBundled": "Gated model — mimari gömülü veri tabanından yüklendi.",
  "warning.gatedUnknown":
    "Gated model ve gömülü veri tabanında yok — mimariyi aşağıdan manuel gir.",
  "warning.configFailed": "Modelin config'i okunamadı — mimariyi aşağıdan manuel gir.",
  "warning.archFromBase": "Mimari base model'den yüklendi (bu repo'nun kendi config'i yok).",

  "quality.wd.fp32": "Tam hassasiyet. BF16'nın iki katı bellek, çıkarımda pratik bir kazanç yok — FP32 ile servis eden neredeyse yok.",
  "quality.wd.fp16": "Referans nokta. Aşağıdaki kalite notları buna göre.",
  "quality.wd.bf16": "Referans nokta. Aşağıdaki kalite notları buna göre.",
  "quality.wd.fp8": "Çoğu işte referansa yakın; ancak donanım desteği (Hopper / Ada ve sonrası) ve FP8 için yayımlanmış ya da kalibre edilmiş bir checkpoint ister.",
  "quality.wd.int8": "Sadece ağırlık quantize edilip düzgün kalibre edildiğinde kayıp genelde küçük ve işe göre değişir. Aktivasyonları da quantize etmek riskin arttığı yer.",
  "quality.wd.int4": "En büyük kalite riski. İyi hazırlanmış bir AWQ / GPTQ checkpoint'i sohbette naif yuvarlamadan çok daha iyi dayanır; ama önce kod, matematik ve uzun bağlamlı akıl yürütme bozulur — sahaya çıkmadan kendi işinde doğrula.",
  "quality.kv.fp16": "Cache için referans hassasiyet.",
  "quality.kv.bf16": "Cache için referans hassasiyet.",
  "quality.kv.fp8": "Cache'i yarıya indirir. Doğruluk bedeli context uzadıkça büyür; kısa değil, uzun girdilerle doğrula.",
  "controls.step": "Hassasiyet & yük",
  "controls.weightQuant": "Ağırlık quantization",
  "controls.kvPrecision": "KV cache hassasiyeti",
  "controls.kvHint": "servis tarafı · FP8 KV'yi yarıya indirir",
  "controls.context": "Context penceresi (token / dizi)",
  "controls.contextMax": "model maks {n}",
  "controls.tok": "token",
  "controls.users": "Eşzamanlı kullanıcı / istek",
  "controls.usersHint": "cache'te tutulan batch",
  "controls.overhead": "Ek yük (aktivasyon + parçalanma)",

  "results.title": "Tahmini VRAM",
  "results.totalRequired": "toplam gerekli",
  "seg.weights": "Ağırlıklar",
  "seg.kv": "KV cache",
  "seg.act": "Aktivasyon",
  "seg.cuda": "CUDA/ek yük",
  "stat.weights": "Ağırlıklar",
  "stat.kvTotal": "KV cache (toplam)",
  "stat.kvSeq": "KV / dizi",
  "stat.kvToken": "KV / token",
  "stat.headDim": "head dim {n}",

  "gpu.step": "GPU uyumu",
  "gpu.pickPrompt": "Bu modelle sınamak için bir GPU seç",
  "gpu.pickHint":
    "Bu model yaklaşık {x} istiyor. Aşağıdan bir kart seçtiğinde sığıp sığmadığını, kaç eşzamanlı kullanıcı kaldırdığını, ne kadar bağlam taşıyabildiğini ve beklenen üretim hızını görürsün.",
  "gpu.usableHint": "VRAM'in %{p}'i kullanılabilir varsayılır",
  "gpu.fits": "sığar ✓",
  "gpu.needs": "{n}× GPU gerekir",
  "gpu.usage": "{x} / {y} GB (kullanılabilirin %{p}'i)",
  "gpu.maxUsers": "Maks eşzamanlı kullanıcı",
  "gpu.atCtx": "{x} ctx'te",
  "gpu.maxContext": "Maks context / kullanıcı",
  "gpu.atUsers": "{n} eşzamanlıda",
  "gpu.tokens": "token",
  "gpu.weightsNoFit": "ağırlıklar sığmıyor",
  "gpu.recTitle": "Ne işe yarar",
  "gpu.recSmallest": "sığan en küçük cihaz",
  "gpu.recQuant": "{gpu} kalır — {x}",
  "gpu.recNone": "Bu yapılandırma veritabanındaki hiçbir tek cihaza sığmıyor ve daha hafif bir hassasiyet de altına indirmiyor. Context'i kısalt, eşzamanlılığı düşür ya da tensor parallel planla.",
  "gpu.recSmaller": "{name} ({mem} GB) da yeterdi.",
  "gpu.recSwitch": "Geç",
  "gpu.decodeSpeed": "Üretim hızı",
  "gpu.tpsSingle": "tok/s, tek kullanıcı",
  "gpu.tpsBatch": "tok/s kullanıcı başına · toplam ~{total}",
  "gpu.speedNote": "Bant genişliğine bağlı tahmin, tepe değerin %{p}'i: her token aktif ağırlıkları ve KV cache'i okur. Prefill (ilk token süresi) işlem gücüne bağlıdır, dahil değildir.",
  "gpu.mig": "MIG profili",
  "gpu.noFitSingle": "sığmıyor",
  "gpu.tpTitle": "{n}x kart, tensor parallel demek",
  "gpu.tpHeadsOk": "{n}, {kv} KV head'e bölünüyor; vLLM --tensor-parallel-size {n} kabul eder.",
  "gpu.tpHeads": "TP boyutu {kv} KV head'e bölünmeli — bu sayı yerine {ok} kullan.",
  "gpu.tpNvlink": "Tüketici kartlarında çoğunlukla NVLink/P2P yoktur; tek modeli bu kartlara bölmek yavaş kalır.",
  "gpu.tpOverhead": "Bellek tam bölünmez: aktivasyonlar ve iletişim tamponları her kartta tekrarlanır.",
  "gpu.tpLink": "Bu kurulumu vLLM sayfasında aç",
  "gpu.unifiedSingle": "Unified bellekli cihaz tek parçadır — tek modeli servis etmek için ikincisi eklenemez. Hassasiyeti düşür, context'i kısalt ya da daha çok bellekli bir cihaz seç.",
  "gpu.migOff": "Tam GPU (MIG yok)",
  "gpu.cardFits": "sığar · %{p}",
  "gpu.cardNeeds": "{n}× gerekir",
  "gpu.cardOverBudget": "bütçe aşımı",
  "gpu.unified": "{total} GB unified → ~{usable} GB kullanılabilir · {bw} GB/s",
  "gpu.bw": "{bw} GB/s",
  "gpu.showNonFit": "Uymayanları göster ({n})",
  "gpu.hideNonFit": "Uymayanları gizle",
  "gpu.noneFit": "Bu kademede hiçbiri bu modele sığmıyor",
  "cat.consumer": "Tüketici",
  "cat.workstation": "İş istasyonu",
  "cat.datacenter": "Veri merkezi",
  "cat.apple": "Apple",
  "cat.apu": "Yapay zekâ PC (unified)",

  "method.summary": "Sayılar nasıl hesaplanıyor",
  "method.weightsTerm": "Ağırlıklar",
  "method.weightsText":
    "= parametre × byte/parametre (FP16/BF16 = 2, FP8/INT8 = 1, INT4 = 0.5). Mixture-of-Experts modellerde tüm uzmanlar yüklenir, dolayısıyla aktif alt küme değil toplam parametre kullanılır.",
  "method.kvTerm": "KV cache",
  "method.kvText":
    "= 2 × katman × kv_head × head_dim × byte × context × eşzamanlılık. Grouped-Query Attention (kv_head < attn_head) bunu ciddi ölçüde küçültür — her modelin config'inden okunur. Multi-head latent attention (DeepSeek) ise token başına katman × (kv_lora_rank + qk_rope_head_dim) × byte saklar.",
  "method.overheadTerm": "Ek yük",
  "method.overheadText":
    "aktivasyon + parçalanmayı (ayarlanabilir %) ve sabit bir CUDA context payını ekler. GPU uyumu, nominal VRAM'in ~%95'inin kullanılabilir olduğunu varsayar.",
  "method.disclaimer":
    "Tahminler planlama içindir, garanti değildir. Gerçek kullanım; servis motoruna (vLLM, TGI, llama.cpp) ve onun paged-attention verimliliğine göre değişir.",

  "footer.builtBy": "Yapan:",
  "footer.privacy": "Hesaplama tarayıcında yapılır — hesap yok, sunucu yok. Ziyaretler anonim ve çerezsiz sayılır.",
  "link.github": "GitHub",
  "link.linkedin": "LinkedIn",
  "link.hf": "Hugging Face",

  "nav.sizing": "VRAM Hesabı",
  "nav.fit": "Görev Uygunluğu",

  "fit.title": "Model ↔ Görev Uygunluğu",
  "fit.subtitle":
    "Bu model işi gerçekten yapar mı? Bir model ve kullanım amacını seç — LLMScale, modelin gerçek özelliklerinden (boyut, context, ayar, kip) uygunluğu skorlar ve her kriteri açıklar.",
  "fit.pickTask": "Görevini seç",
  "fit.scoreLabel": "Yetenek eşleşmesi",
  "fit.empty": "Uygunluğu görmek için bir model ve görev seç.",
  "fit.scoreUnit": "kontrol edilen kriterlerin",
  "fit.methodNote": "Modelin beyan ettiklerinden okunur — boyut, context, ince ayar, modalite. Cevap kalitesini, kaynağa bağlılığı ya da halüsinasyon oranını göremez; yüksek eşleşme “bu iş için tasarlanmış” demektir, “bu işte iyi” demek değil. Onu ancak kendi değerlendirmen söyler.",
  "fit.criteriaTitle": "Bu skorun nedeni",

  "fit.verdict.great": "Bu iş için tasarlanmış",
  "fit.verdict.good": "Kullanılabilir",
  "fit.verdict.weak": "Kâğıt üstünde zayıf",
  "fit.verdict.poor": "Yanlış araç",

  "fit.task.chat": "Sohbet / asistan",
  "fit.task.code": "Kod üretimi",
  "fit.task.rag": "RAG / belge S-C",
  "fit.task.summarize": "Uzun belge özet",
  "fit.task.agent": "Ajan / araç kullanımı",
  "fit.task.reasoning": "Akıl yürütme & matematik",
  "fit.task.multilingual": "Çok dilli",
  "fit.task.vision": "Görsel / çok kipli",
  "fit.task.embeddings": "Embedding / arama",
  "fit.task.edge": "Cihaz üstü / edge",
  "fit.task.throughput": "Yüksek throughput servis",

  "fit.crit.modality": "Model türü",
  "fit.crit.instruct": "Talimat ayarı",
  "fit.crit.size": "Model boyutu",
  "fit.crit.context": "Context penceresi",
  "fit.crit.code": "Kod yeteneği",
  "fit.crit.reasoning": "Akıl yürütme",
  "fit.crit.multilingual": "Çok dillilik",
  "fit.crit.efficiency": "Servis verimliliği",

  "fit.msg.modalityGen": "Üretken metin modeli",
  "fit.msg.modalityEmbedding": "Bu bir embedding modeli — üretim için tasarlanmamış",
  "fit.msg.modalityReranker": "Bu bir reranker/sınıflandırıcı — üretim için değil",
  "fit.msg.modalityUnknownGen": "Üretken model olduğu doğrulanamadı",
  "fit.msg.instructYes": "Sohbet / talimat ayarlı",
  "fit.msg.instructBase": "Base model — -Instruct sürümünü tercih et",
  "fit.msg.instructUnknown": "Talimat ayarı belirsiz",
  "fit.msg.size": "{params} (önerilen ≥ {ideal}B)",
  "fit.msg.context": "{ctx} token (önerilen ≥ {ideal}k)",
  "fit.msg.contextUnknown": "Context uzunluğu bilinmiyor",
  "fit.msg.codeYes": "Koda özel",
  "fit.msg.codeNo": "Koda özel değil",
  "fit.msg.reasonYes": "Akıl yürütme / matematik ayarlı",
  "fit.msg.reasonNo": "Akıl yürütmeye özel değil — boyuta dayanır",
  "fit.msg.multiYes": "Çok dilli",
  "fit.msg.multiNo": "İngilizce ağırlıklı görünüyor",
  "fit.msg.visionYes": "Çok kipli (görsel) model",
  "fit.msg.visionNo": "Görsel yeteneği yok — -VL / çok kipli model seç",
  "fit.msg.embedYes": "Embedding modeli",
  "fit.msg.embedNo": "Embedding modeli değil — örn. BGE, E5, Qwen3-Embedding kullan",
  "fit.msg.edgeSize": "{params} — cihazda küçük olan daha iyi",
  "fit.msg.effMoE": "MoE — düşük aktif hesap, güçlü throughput",
  "fit.msg.effDense": "{params} yoğun — token başına daha ağır",

  "nav.vllm": "vLLM Parametreleri",
  "nav.decode": "İsim Çözücü",
  "nav.anatomy": "Model Anatomisi",
  "nav.compare": "Model Karşılaştırma",
  "nav.train": "İnce ayar",
  "train.subtitle":
    "İnce ayar GPU belleğinde neye mal olur? Eğitimde KV cache yoktur ama gradyanlar, optimizer durumu ve geri yayılım için saklanan aktivasyonlar eklenir — bu yüzden tek kartta servis edebildiğin bir model çoğu zaman o kartta eğitilemez.",
  "train.setup": "Eğitim kurulumu",
  "train.mode": "Yöntem",
  "train.mode.full": "Tam",
  "train.modeNote.full": "Her parametre eğitilir: ağırlık, gradyan ve Adam durumu için parametre başına 16 bayt. Açık ara en ağır seçenek.",
  "train.modeNote.lora": "Taban bf16'da dondurulup yalnız küçük bir adapter eğitilir; gradyan ve optimizer belleği neredeyse yok olur. Aktivasyonlar olmaz.",
  "train.modeNote.qlora": "LoRA gibi, ama donmuş taban 4-bit tutulur — yerleşik ağırlıkların kabaca dörtte biri, tabanda bir miktar kalite bedeliyle.",
  "train.rank": "LoRA rank",
  "train.target": "Adapter nerede",
  "train.target.attn": "Attention",
  "train.target.all": "Tüm linear",
  "train.batch": "Batch boyutu (cihaz başına)",
  "train.seq": "Dizi uzunluğu",
  "train.ckpt": "Gradient checkpointing",
  "train.ckptHint": "saklamak yerine yeniden hesapla",
  "train.on": "Açık",
  "train.off": "Kapalı",
  "train.results": "Gereken bellek",
  "train.totalRequired": "cihaz başına",
  "train.seg.base": "Taban ağırlıklar",
  "train.seg.grads": "Gradyanlar",
  "train.seg.optim": "Optimizer",
  "train.seg.act": "Aktivasyonlar",
  "train.seg.overhead": "Ek yük",
  "train.noteFull": "Baskın kalem optimizer: Adam bir fp32 ana kopya ve iki moment tutar — bf16 ağırlıkların kendisinin üç katı.",
  "train.noteAdapter": "Tabanı dondurmak gradyan ve optimizer belleğinin neredeyse tamamını kaldırır, ama geri yayılım yine her katmandan geçer — yani aktivasyonlar tam ince ayarla aynı yer tutar. Elinde kalan kollar: checkpointing, batch boyutu ve dizi uzunluğu.",
  "train.gpuFit": "Hangi GPU'lar yeter",
  "train.shardNote": "Servisin aksine burada parçalama norm: FSDP ya da DeepSpeed ZeRO-3 parametreleri, gradyanları ve optimizer durumunu rank'lara böler, bu yüzden bu toplam neredeyse doğrusal bölünür. Aktivasyonlar küçülmez — onlar için batch ya da dizi uzunluğunu düşür.",
  "train.method": "Karma hassasiyetli Adam, parametre başına 16 bayt (bf16 ağırlık + bf16 gradyan + fp32 ana kopya, m ve v). Aktivasyonlar Korthikanti vd. 2022'ye göre katman ve token başına ~34 bayt (flash-attention varsayılır), tam yeniden hesaplamada 2 bayt. Gerçek koşular framework ve çekirdek seçimlerine göre değişir; bunu planlama rakamı olarak al.",
  "theme.dark": "Koyu",
  "theme.light": "Açık",
  "theme.glass": "Cam",
  "h1.sizing": "LLM VRAM hesaplayıcı — model ağırlıkları, KV cache ve GPU uyumu",
  "h1.train": "İnce ayar VRAM'i — LoRA, QLoRA ve tam ince ayar belleği",
  "h1.fit": "Görev uyumu — bu LLM bu iş için doğru mu?",
  "h1.anatomy": "Model anatomisi — bir LLM'in parametreleri ve belleği nereye gidiyor",
  "h1.compare": "LLM'leri yan yana karşılaştır",
  "h1.decode": "LLM model adı çözücü",
  "h1.vllm": "vLLM parametre yardımcısı — ayarlanmış vllm serve komutu",
  "h1.learn": "LLM 101 — bir dil modeli nasıl çalışır",
  "nav.learn": "LLM 101",
  "compare.subtitle":
    "2–4 modeli yan yana koy — spec'ler, yetenekler ve görev-bazlı uygunluk — hangisinin ne için daha iyi olduğunu gör, canlı Hugging Face verisinden.",
  "compare.pickTitle": "Modeller",
  "compare.count": "{n} / {max}",
  "compare.search": "+ Model ekle…",
  "compare.max": "En fazla 4 model",
  "compare.empty": "Karşılaştırmak için model ekle.",
  "compare.loadingCol": "yükleniyor…",
  "compare.err": "bulunamadı",
  "compare.remove": "Kaldır",
  "compare.dense": "dense",
  "compare.sec.identity": "Kimlik & popülerlik",
  "compare.sec.arch": "Mimari & bellek",
  "compare.sec.caps": "Yetenekler",
  "compare.sec.fit": "Görev uygunluğu",
  "compare.fitHint": "puan 0–100 · en iyi vurgulu",
  "compare.row.params": "Parametre",
  "compare.row.moe": "MoE (aktif / toplam)",
  "compare.row.context": "Context",
  "compare.row.license": "Lisans",
  "compare.row.downloads": "İndirme (30g)",
  "compare.row.likes": "Beğeni",
  "compare.row.updated": "Güncelleme",
  "compare.row.base": "Base model",
  "compare.row.precision": "Hassasiyet",
  "compare.row.layers": "Katman",
  "compare.row.hidden": "Hidden boyut",
  "compare.row.heads": "Attn / KV head",
  "compare.row.headDim": "Head dim",
  "compare.row.vocab": "Vocab",
  "compare.row.weights": "Ağırlıklar (native)",
  "compare.row.kvtoken": "KV / token",
  "compare.row.vram8k": "VRAM @ 8k · 1 kullanıcı",
  "compare.cap.instruct": "Talimat-ayarlı",
  "compare.cap.code": "Kod",
  "compare.cap.math": "Matematik",
  "compare.cap.reasoning": "Akıl yürütme",
  "compare.cap.vision": "Görsel",
  "compare.cap.multilingual": "Çok dilli",
  "compare.cap.embedding": "Embedding",
  "compare.tip.params": "Toplam parametre. Fazla = daha yetenekli/bilgili, ama daha ağır — daha çok VRAM, daha yavaş, daha maliyetli.",
  "compare.tip.moe": "MoE aktif / toplam uzman. Tüm uzmanlar VRAM'e sığmalı (toplam), ama token başına birkaçı çalışır (aktif) — hızlı hesapla büyük kapasite.",
  "compare.tip.context": "Modelin işleyebildiği maksimum token. Uzun = büyük belge / RAG, ama KV cache büyür → daha çok VRAM.",
  "compare.tip.license": "Kullanım lisansı. İzin verici (Apache/MIT) = az kısıt; bazı lisanslar ticari veya gated kullanımı sınırlar.",
  "compare.tip.downloads": "30 günlük indirme — benimsenme/popülerlik sinyali, kalite değil. Fazla = daha geniş topluluk kullanımı & destek.",
  "compare.tip.likes": "Hub beğenisi — topluluk ilgisi sinyali, kalite ölçüsü değil.",
  "compare.tip.updated": "Son güncelleme tarihi. Yeni = muhtemelen düzeltme/iyileştirme, ama çok yeni daha az denenmiş olabilir.",
  "compare.tip.base": "Bunun fine-tune / quantize edildiği temel model. Soyu gösterir; yetenekler büyük ölçüde ondan miras alınır.",
  "compare.tip.precision": "Doğal ağırlık formatı. Düşük bit (INT4/FP8) = daha küçük & hızlı, BF16/FP16'ya göre küçük doğruluk ödünü.",
  "compare.tip.layers": "Transformer bloğu (derinlik). Fazla = daha çok kapasite, ama daha yüksek gecikme ve token başına daha çok KV cache.",
  "compare.tip.hidden": "Hidden boyut (genişlik). Büyük = daha çok temsil gücü, ama daha çok parametre & bellek.",
  "compare.tip.heads": "Attention / KV head. Az KV head (GQA) = çok daha küçük KV cache, minimal kalite kaybı.",
  "compare.tip.headDim": "Attention head başına boyut. Büyük head_dim, token başına KV cache boyutunu artırır.",
  "compare.tip.vocab": "Tokenizer sözlük boyutu. Büyük = daha iyi çok dilli kapsam, ama daha büyük embedding matrisi.",
  "compare.tip.weights": "Native hassasiyette ağırlık belleği. Küçük = küçük GPU'lara sığar; büyük modeller genelde daha yetenekli.",
  "compare.tip.kvtoken": "Token başına KV cache (FP16). Küçük = GPU başına daha çok eşzamanlı kullanıcı / daha uzun context (GQA yardımcı olur).",
  "compare.tip.vram8k": "8k context, 1 kullanıcıda tahmini toplam VRAM. Düşük = daha ucuz servis / küçük GPU'lara sığar.",
  "compare.tip.capGeneric": "✓ = model {cap} için ayarlı/uygun; ✗ = bu konuda özelleşmemiş.",
  "compare.tip.taskGeneric": "{task} için uygunluk (0–100). Yüksek = daha uygun; satırdaki en iyi model vurgulanır.",
  "anatomy.subtitle":
    "Modelin görsel röntgeni: parametreleri nerede, nasıl quantize edilmiş, attention yapısı ve KV cache nasıl büyüyor — hepsi canlı Hugging Face verisinden.",
  "anatomy.loading": "Model anatomisi yükleniyor…",
  "anatomy.empty": "Anatomiyi görmek için bir model seç.",
  "anatomy.disclaimer":
    "Parametre dağılımı config'ten türetilir — embedding + attention kesin; feed-forward / expert bloğu kalandır. Yönlendirme amaçlı tahmindir.",
  "anatomy.params.title": "Parametre dağılımı",
  "anatomy.params.embeddings": "Embedding",
  "anatomy.params.attention": "Attention",
  "anatomy.params.mlp": "Feed-forward (MLP)",
  "anatomy.params.experts": "Uzmanlar (MoE)",
  "anatomy.params.totalSub": "toplam parametre",
  "anatomy.params.activeNote":
    "MoE: token başına yalnızca ~{active} parametre ({experts} uzmandan {perTok} tanesi) aktif — ama hepsi VRAM'e sığmalı.",
  "anatomy.precision.title": "Hassasiyet & bellek",
  "anatomy.precision.mix": "Dağıtımdaki hassasiyet karışımı",
  "anatomy.precision.mixNA": "Bu repo için hassasiyet karışımı yok (gated ya da safetensors indeksi yok).",
  "anatomy.precision.native": "doğal",
  "anatomy.precision.memTitle": "Ağırlıklar tamamen şu olsaydı…",
  "anatomy.arch.title": "Mimari",
  "anatomy.arch.layers": "Katman",
  "anatomy.arch.hidden": "Hidden boyut",
  "anatomy.arch.headDim": "Head dim",
  "anatomy.arch.heads": "Attn / KV head",
  "anatomy.arch.mlpRatio": "MLP genişleme",
  "anatomy.arch.context": "Context",
  "anatomy.arch.vocab": "Vocab",
  "anatomy.arch.experts": "Uzman (aktif / toplam)",
  "anatomy.arch.expertsSub": "token başına / toplam",
  "anatomy.arch.gqaTitle": "Attention gruplama",
  "anatomy.arch.gqaNote": "GQA: {q} sorgu head'i {kv} KV head'ini paylaşır ({ratio}:1) — KV cache'i ~{ratio}× düşürür.",
  "anatomy.arch.mhaNote": "MHA: {n} sorgu head'i, her biri kendi KV head'ine sahip (GQA paylaşımı yok).",
  "anatomy.arch.hint": "bir token modelde nasıl akıyor",
  "anatomy.diagram.input": "Tokenlaştırılmış girdi",
  "anatomy.diagram.embed": "Token embedding",
  "anatomy.diagram.attn": "Gruplu-sorgu attention",
  "anatomy.diagram.attnMha": "Çok-başlı attention",
  "anatomy.diagram.mlp": "Feed-forward · SwiGLU",
  "anatomy.diagram.moe": "Uzman Karışımı (MoE)",
  "anatomy.diagram.finalNorm": "Final norm",
  "anatomy.diagram.output": "Çıkış projeksiyonu",
  "anatomy.diagram.block": "Transformer bloğu",
  "anatomy.diagram.blockN": "× {n}",
  "anatomy.diagram.expertsDetail": "{act}/{tot} uzman",
  "anatomy.diagram.activeSub": "aktif parametre",
  "anatomy.diagram.totalSub": "toplam parametre",
  "anatomy.diagram.flow": "Veri aşağıdan → yukarı akar · bir token'ın yolu",
  "anatomy.diagram.expertsLabel": "aktif / toplam uzman",
  "anatomy.diagram.moeLabel": "uzman karışımı",
  "anatomy.diagram.swigluLabel": "SwiGLU ara katman",
  "anatomy.diagram.logitsLabel": "çıkış logits",
  "anatomy.diagram.headDimLabel": "head boyutu",
  "anatomy.diagram.vocabLabel": "sözlük boyutu",
  "anatomy.diagram.dimLabel": "embedding boyutu",
  "anatomy.kv.title": "KV cache büyümesi",
  "anatomy.kv.gqaLegend": "Bu model",
  "anatomy.kv.mhaLegend": "GQA olmadan (MHA)",
  "anatomy.kv.noteGqa": "GQA, KV cache'i düz çok-başlı attention'a göre ~{ratio}× küçük tutar.",
  "anatomy.kv.noteMha": "Context büyüdükçe sekans başına KV cache (FP16).",
  "anatomy.meta.downloads": "İndirme (30g)",
  "anatomy.meta.likes": "Beğeni",
  "anatomy.meta.license": "Lisans",
  "anatomy.meta.updated": "Güncelleme",
  "anatomy.meta.size": "Repo boyutu",
  "anatomy.meta.base": "Şundan türetilmiş / quantize",
  "decode.subtitle":
    "Bir model adındaki her parça ne anlama geliyor? Bir model yaz ya da seç — her token (boyut, quantization, varyant…) renklendirilip açıklanır. Üzerine gel, parlasın.",
  "decode.input": "Model adı",
  "decode.breakdown": "Parçalar",
  "decode.hint": "Bir token'ın üzerine gel, anlamı parlasın.",
  "decode.empty": "Çözmek için bir model adı yaz.",
  "vllm.subtitle":
    "Ayarlanmış bir `vllm serve` komutu üret. Bir model, neyi optimize ettiğini ve iş tipini seç — LLMScale en iyi performans, doğruluk ve güvenilirlik için parametreleri önerir ve kopyalanabilir komut verir.",
  "vllm.pickPriority": "Neyi optimize et",
  "vllm.pickTask": "İş tipi",
  "vllm.noMetal": "{gpu} vLLM ile servis edemez — Metal backend yok. H100 80GB'ye geçildi; o cihazın bellek hesabı sizing sayfasında duruyor.",
  "vllm.gpuCount": "GPU sayısı",
  "vllm.maxlen": "Maks context (max-model-len)",
  "vllm.commandTitle": "Önerilen komut",
  "vllm.copy": "Kopyala",
  "vllm.copied": "Kopyalandı ✓",
  "vllm.copyK8s": "K8s argümanları",
  "vllm.k8sHint": "Kubernetes argümanı olarak kopyala: her satır --key=value, serve/model yok.",
  "vllm.model": "model",
  "vllm.flagsTitle": "Her parametre ne yapıyor",
  "vllm.warningsTitle": "Notlar & uyarılar",
  "vllm.empty": "vLLM parametreleri için bir model seç.",

  "vllm.prio.balanced": "Dengeli",
  "vllm.prio.throughput": "Throughput",
  "vllm.prio.latency": "Düşük gecikme",
  "vllm.prio.accuracy": "Maks doğruluk",
  "vllm.prio.memory": "Bellek-kısıtlı",

  "vllm.task.chat": "Sohbet / asistan",
  "vllm.task.rag": "RAG / uzun context",
  "vllm.task.code": "Kod",
  "vllm.task.tool": "Araç kullanımı / ajan",
  "vllm.task.structured": "Yapısal JSON",
  "vllm.task.vision": "Görsel / çok kipli",
  "vllm.task.reasoning": "Akıl yürütme",

  "vllm.r.maxlen": "Context penceresini sınırlar — modelin tam maksimumuna göre KV cache'i serbest bırakır.",
  "vllm.r.tp": "Modeli GPU'lara böler (tensor paralelliği).",
  "vllm.r.ep": "MoE katmanları için GPU'lar arası uzman paralelliği.",
  "vllm.r.gpuutil": "vLLM'in ağırlık + KV cache için kullanabileceği VRAM oranı.",
  "vllm.r.kvfp8": "FP8 KV cache, cache belleğini ~yarıya indirir — daha fazla/uzun dizi sığar.",
  "vllm.r.maxbatched": "Büyük prefill batch'i throughput'u en üst düzeye çıkarır.",
  "vllm.r.maxbatchedLat": "Küçük prefill batch'i token-arası gecikmeyi düşürür.",
  "vllm.r.maxseqs": "Throughput için çok sayıda eşzamanlı diziye izin verir.",
  "vllm.r.maxseqsLat": "Az eşzamanlı dizi gecikmeyi düşük tutar.",
  "vllm.r.maxseqsMem": "KV cache belleğini sınırlamak için eşzamanlılığı kısıtlar.",
  "vllm.r.chunked": "Chunked prefill, uzun prompt'ların decode'u durdurmasını önler.",
  "vllm.r.prefix": "Prefix caching, paylaşılan sistem/context ön-eklerini yeniden kullanır.",
  "vllm.r.tool": "Otomatik araç/fonksiyon çağrısını etkinleştirir.",
  "vllm.r.toolparser": "Bu model ailesine uygun ayrıştırıcı ({parser}).",
  "vllm.r.guided": "Hızlı, güvenilir JSON/gramer çıktısı için xgrammar arka ucu.",
  "vllm.r.mm": "Çok kipli girdi için prompt başına görsel sınırı.",
  "vllm.r.dtype": "En iyi doğruluk için tam BF16 ağırlıklar.",
  "vllm.r.seed": "Tekrarlanabilir, güvenilir çıktı için sabit seed.",

  "vllm.w.ctxcap": "İstenen context modelin maksimumunu ({max}) aşıyor — vLLM reddeder ya da rope scaling gerekir.",
  "vllm.w.fp8acc": "FP8 KV cache uzun-context görevlerde doğruluğu düşürebilir — üretimden önce doğrula.",
  "vllm.w.kvfull": "Maksimum doğruluk için KV cache tam hassasiyette (auto) tutuluyor.",
  "vllm.w.template": "Bu ayrıştırıcı genelde modele özel --chat-template ister (vLLM examples/ klasörü).",
  "vllm.w.parserUnknown": "Tool-call ayrıştırıcısı tespit edilemedi — --tool-call-parser'ı modeline göre ayarla.",
  "vllm.w.trust": "Çoğu çok kipli model ayrıca --trust-remote-code ister.",
  "vllm.w.quant": "Önceden quantize edilmiş model ({q}) — vLLM otomatik algılar; --quantization gerekmez.",
  "vllm.w.gguf": "vLLM'de GGUF desteği deneyseldir — safetensors/native repo önerilir.",
  "vllm.w.seqcap": "--max-num-seqs {fit} ile sınırlandı: {ctx} token bağlamda KV cache ancak bu kadarını tutuyor. Artırmak yalnızca kuyruğu uzatır.",
  "vllm.w.fit": "~{need} GiB gerekiyor, ~{have} GiB var — GPU ekle (≈{gpus}), quantize et, context'i kısalt ya da FP8 KV kullan.",
  "vllm.w.mig": "MIG = tek izole GPU dilimi; MIG'ler arası tensor-parallel desteklenmez. Instance'ı CUDA_VISIBLE_DEVICES=MIG-… ile sabitle.",

  // Her aracın altındaki açıklama (components/About.tsx).
  "about.faq": "Sık sorulanlar",
  "about.sizing.title": "Bu hesaplayıcının varsayımları",
  "about.sizing.p1": "LLMScale her modelin mimarisini Hugging Face Hub'daki config.json dosyasından okur — katman sayısı, attention ve key-value head sayısı, head boyutu — ve GPU belleğini yalnızca parametre sayısından değil, bunlardan hesaplar. Tarayıcının config'ini okuyamadığı Llama, Gemma ve Mistral gibi erişimi kısıtlı modeller yerleşik bir veritabanından gelir; kendi config'i olmayan depolar, örneğin GGUF kopyaları, base_model üzerinden çözülür.",
  "about.sizing.p2": "Her kartta nominal belleğin %95'i kullanılabilir kabul edilir. Unified bellekli cihazlarda havuzun tamamı yerine gerçekçi bir pay kullanılır: Apple Mac'lerde belleğin %75'i, Strix Halo'da 128 GB'ın 96'sı, DGX Spark'ta 128 GB'ın 120'si. Üretim (decode) hızı bellek bant genişliğinden %80 verimlilikle tahmin edilir; prompt işleme (prefill) modellenmez. Sayılar kapasite planlaması içindir — servis motoru ve paged-attention verimliliği gerçek değeri yine değiştirir.",
  "about.sizing.q1": "70B bir model kaç GB VRAM ister?",
  "about.sizing.a1": "Yalnızca ağırlıklar BF16'da yaklaşık 130 GiB, FP8'de 65 GiB, INT4'te 33 GiB tutar (70 milyar parametre × 2, 1 ya da 0,5 byte). KV cache ve ek yük bunun üstüne gelir; ikisi de context penceresine ve kullanıcı sayısına bağlıdır — hesaplayıcının bulduğu da budur.",
  "about.sizing.q2": "Context penceresi sonucu neden bu kadar değiştiriyor?",
  "about.sizing.a2": "KV cache, context uzunluğu ve eşzamanlı kullanıcı sayısıyla doğrusal büyür. Llama 3.1 8B, FP16'da token başına 131.072 byte saklar: tek kullanıcı için 8k token'da 1 GiB, 128k'da 16 GiB — 8k'da 16 kullanıcıyla da yine 16 GiB.",
  "about.sizing.q3": "Mixture-of-Experts modeller daha az bellek mi ister?",
  "about.sizing.a3": "Bellek açısından hayır. Tüm uzmanların yüklenmesi gerekir, bu yüzden bellek toplam parametre sayısından hesaplanır. Her token için uzmanların yalnızca bir kısmı çalışır; MoE modellerin boyutlarına göre hızlı üretmesinin nedeni budur.",
  "about.sizing.q4": "DeepSeek'in KV cache'i nasıl hesaplanıyor?",
  "about.sizing.a4": "DeepSeek-V2 ve V3, multi-head latent attention (MLA) kullanır: her head için key ve value yerine katman başına tek bir sıkıştırılmış latent saklar. Hesaplayıcı config'den kv_lora_rank ve qk_rope_head_dim değerlerini okur ve token başına katman × (kv_lora_rank + qk_rope_head_dim) × byte kullanır. DeepSeek-V3 için 8k context'te bu 0,54 GiB eder; alışılmış formül 13,34 GiB verirdi.",
  "about.train.title": "İnce ayar belleği nasıl hesaplanıyor",
  "about.train.p1": "İnce ayar, bellekte ağırlıklardan fazlasını tutar. Eğitilen her parametre için bir gradyan ve optimizer durumu gerekir; ileri geçiş de geri yayılım için aktivasyonları saklar. LoRA ve QLoRA temel modeli dondurup küçük adaptörler eğitir, böylece gradyan ve optimizer durumu adaptör boyutuna iner; QLoRA ayrıca dondurulmuş temel modeli 4-bit NF4 olarak saklar.",
  "about.train.f1": "temel ağırlıklar = parametre × 2 byte (BF16) ya da × 0,516 byte (QLoRA NF4)",
  "about.train.f2": "gradyanlar = eğitilen parametre × 2 byte",
  "about.train.f3": "optimizer (Adam) = eğitilen parametre × 12 byte: FP32 ana ağırlıklar + iki moment",
  "about.train.f4": "aktivasyonlar = katman × dizi uzunluğu × batch × hidden boyutu × 34 byte; gradient checkpointing ile × 2",
  "about.train.f5": "toplam = temel + gradyanlar + optimizer + aktivasyonlar + 1 GiB ek yük",
  "about.train.p2": "Tam ince ayarda her parametre eğitilir; LoRA'da sayı, rank ve hedef modüllerden — attention projeksiyonları ya da tüm lineer katmanlar — çıkar. Aktivasyonlarda flash attention varsayılır. Motor yayımlanmış iki sonuca karşı doğrulanır: ZeRO makalesinin karışık hassasiyetli Adam için parametre başına 16 byte'ı ve QLoRA'nın 65B bir modeli tek 48 GB kartta eğitmesi; motor bunu 43,3 GiB olarak hesaplar.",
  "about.train.q1": "Tam ince ayar kaç GB VRAM ister?",
  "about.train.a1": "Aktivasyonlardan önce parametre başına yaklaşık 16 byte: 2'si ağırlık, 2'si gradyan, 12'si Adam. 7B bir model için bu kabaca 104 GiB eder; tam ince ayarın genelde birden çok GPU ya da ZeRO-3/FSDP ile paylaştırma gerektirmesinin nedeni budur.",
  "about.train.q2": "LoRA mı QLoRA mı — bellek farkı ne?",
  "about.train.a2": "İkisi de aynı adaptörleri eğitir; fark dondurulmuş temel modeldedir. LoRA onu BF16'da (parametre başına 2 byte), QLoRA NF4'te (0,516 byte) tutar. 8B bir modelde yalnızca temel ağırlıklar için bu, yaklaşık 14,9 GiB'a karşı 3,8 GiB demektir.",
  "about.train.q3": "LoRA aktivasyon belleğini azaltır mı?",
  "about.train.a3": "Hayır. İleri geçiş yine modelin tamamından geçer, bu yüzden aktivasyonlar tam ince ayardakiyle aynıdır. Onları azaltan gradient checkpointing'dir: her katmanın yalnızca girdisini tutar — katman, token ve hidden birimi başına 34 yerine 2 byte — ve gerisini yeniden hesaplar.",
  "about.train.q4": "Burada neden KV cache yok?",
  "about.train.a4": "Eğitim dizileri tek geçişte işler ve metin üretirken olduğu gibi adımlar arasında key ve value önbelleği tutmaz; bu yüzden çıkarım hesaplayıcısındaki KV cache terimi burada yer almaz.",
  "about.fit.title": "Uyum puanı nasıl çalışır",
  "about.fit.p1": "Puan kurallara dayanır ve şeffaftır. Hugging Face Hub'ın bir model hakkında söylediklerini — etiketler, pipeline etiketi, depo adı, model türü — parametre sayısı ve maksimum context ile birlikte okur ve bu sinyalleri her görevin ihtiyacıyla karşılaştırır: talimat eğitimi, kod ya da akıl yürütme eğitimi, görsel yetenek, çok dilli veri, yeterli context, uygun boyut.",
  "about.fit.p2": "11 görevin her biri ölçütlerini farklı ağırlıklandırır: RAG context'e (ideali 32k token), cihaz üstü kullanım küçük boyuta dayanır. Genel puan 100 üzerinden ağırlıklı ortalamadır; kesin bir uyumsuzluk — sohbet için bir embedding modeli, görsel iş için yalnızca metin modeli — puanı 25'te sınırlar. 80 ve üstü “Bu iş için tasarlanmış”, 60 ve üstü “Kullanılabilir”, 40 ve üstü “Kâğıt üstünde zayıf”, altı “Yanlış araç” demektir.",
  "about.fit.q1": "Hangi görevler puanlanıyor?",
  "about.fit.a1": "Sohbet ve asistan, kod üretimi, RAG ve belge soru-cevap, uzun belge özetleme, ajan ve araç kullanımı, akıl yürütme ve matematik, çok dilli kullanım, görsel ve çok kipli işler, embedding ve arama, cihaz üstü ve edge, yüksek throughput servis.",
  "about.fit.q2": "Yüksek puan, modelin iyi olduğu anlamına mı gelir?",
  "about.fit.a2": "Modelin o iş için tasarlandığı anlamına gelir, o işte iyi olduğu anlamına değil. Puan cevap kalitesini, dayanaklılığı ya da halüsinasyon oranını göremez — ikisi de uyan iki model arasında yine benchmark'lar ve kendi değerlendirmen karar verir.",
  "about.fit.q3": "Sohbet için instruct model neden daha yüksek puan alıyor?",
  "about.fit.a3": "Base modeller talimat izlemek üzere eğitilmez; bu yüzden sohbet görevi en büyük ağırlığı, %45'i talimat eğitimine verir. Sayfa bunu conversational ya da chat gibi etiketlerden ve adında Instruct, Chat ya da -it geçmesinden anlar.",
  "about.fit.q4": "Yetenekli bir model hak ettiğinden düşük puan alabilir mi?",
  "about.fit.a4": "Evet. Kurallar yalnızca modelin beyan ettiğini görür; etiketi az ya da adı kısa bir model, hiç belirtmediği sinyallerde puan kaybeder. Ölçüt listesine bak: her biri neyin bulunduğunu ve kaç puan getirdiğini gösterir.",
  "about.anatomy.title": "Anatomi neyi gösteriyor",
  "about.anatomy.p1": "Anatomi görünümü, bir modelin parametrelerini bulundukları yere göre ayırır. Embedding'ler kelime dağarcığı tablosudur — giriş ve çıkış embedding'leri paylaşılmıyorsa iki kez sayılır. Attention; query, key, value ve çıkış projeksiyonlarıdır. Geri kalan her şey, çoğunlukla ileri beslemeli ağ ya da uzmanlar, kalan paydır; böylece parçalar her zaman modelin gerçek toplamını verir.",
  "about.anatomy.f1": "embedding = kelime dağarcığı × hidden boyutu (paylaşılmıyorsa × 2)",
  "about.anatomy.f2": "attention = 2 × katman × hidden boyutu × head_dim × (attention head + key-value head)",
  "about.anatomy.f3": "ileri besleme / uzmanlar = toplam parametre − embedding − attention",
  "about.anatomy.f4": "aktif uzmanlar (MoE) = ileri besleme × token başına uzman ÷ uzman sayısı",
  "about.anatomy.p2": "KV cache grafiği tek bir diziyi FP16'da sıfırdan modelin maksimum context'ine kadar, en fazla 128k token için çizer. Grouped-query attention kullanan modellerde kesik çizgi, tam multi-head attention'ın ne kadar tutacağını gösterir — aradaki fark GQA'nın kazandırdığıdır. Hassasiyet kartı ağırlıkların BF16, FP8 ya da INT8 ve INT4'te ne kadar yer tuttuğunu gösterir.",
  "about.anatomy.q1": "Grouped-query attention (GQA) nedir?",
  "about.anatomy.a1": "Birden çok query head, tek bir key ve value head grubunu paylaşır. KV cache query head sayısıyla değil key-value head sayısıyla büyür; 64 query head'i ve 8 key-value head'i olan bir model, tam multi-head attention'a göre 8 kat daha az önbellek tutar.",
  "about.anatomy.q2": "Küçük modellerde embedding'ler neden bu kadar büyük pay alıyor?",
  "about.anatomy.a2": "Embedding tablosu kelime dağarcığı × hidden boyutudur ve günümüzün kelime dağarcıkları büyüktür. Qwen2.5 7B'de embedding'ler yaklaşık 1,09 milyar parametre tutar, attention ise 0,82 milyar; geri kalanın çoğu ileri beslemeli katmanlardadır.",
  "about.anatomy.q3": "MoE bir model neden çok daha az aktif parametre gösteriyor?",
  "about.anatomy.a3": "Her token için yalnızca birkaç uzman çalışır. Aktif sayı; embedding'leri, attention'ı ve bir token'ın gerçekten geçtiği uzman payını sayar — bellekte ise hepsinin tutulması gerekir.",
  "about.anatomy.q4": "Veriler nereden geliyor?",
  "about.anatomy.a4": "Modelin config.json dosyasından ve Hugging Face model API'sinden, tarayıcında canlı olarak. İndirme, beğeni, lisans ve depo boyutu da aynı yerden gelir.",
  "about.compare.title": "Karşılaştırma neyi ölçüyor",
  "about.compare.p1": "Hugging Face Hub'dan iki ile dört modeli yan yana koy. Her sütun diğer sayfalardaki yöntemle çözülür: parametre, uzman, maksimum context, lisans, indirme, beğeni, son güncelleme ve temel model; ağırlıkların yayımlandığı hassasiyet ve kapladıkları yer; FP16'da token başına KV cache; 8k token ve tek kullanıcı için gereken GPU belleği.",
  "about.compare.p2": "Altında Hub'ın beyan ettiği yetenekler — instruct, kod, matematik, akıl yürütme, görsel, çok dilli, embedding — ve 11 görevin tamamı için görev uyum puanı yer alır. Context, indirme, beğeni ve her görev puanında en iyi değer vurgulanır; tüm modellerin eşit olduğu satır sade kalır.",
  "about.compare.q1": "VRAM değeri hesaplayıcıdakiyle aynı mı?",
  "about.compare.a1": "Aynı motordan, sabit bir iş yüküyle gelir: 8k context, tek kullanıcı, FP16 KV cache, %10 ek yük ve 0,75 GiB CUDA context. Kendi context ve kullanıcı sayına göre boyutlandırmak için modeli VRAM hesaplayıcısında aç.",
  "about.compare.q2": "Quantize edilmiş bir model neden bazen BF16 görünüyor?",
  "about.compare.a2": "Hassasiyet quantization config'inden, depo adından, torch_dtype'tan ya da safetensors başlığından tespit edilemezse karşılaştırma BF16 varsayar. Ağırlık boyutu fazla büyük görünüyorsa depoyu kontrol et.",
  "about.compare.q3": "Görevim için hangi model daha iyi?",
  "about.compare.a3": "Görev satırları her modelin o iş için ne kadar uygun yapıldığını puanlar — talimat eğitimi, context, boyut, beyan edilen yetenekler. Cevap kalitesini ölçemezler; kısa liste çıkarmak için kullan, sonra finalistleri kendi prompt'larınla dene.",
  "about.compare.q4": "Kaç model karşılaştırabilirim?",
  "about.compare.a4": "Aynı anda en fazla dört. Seçim sayfa adresinde tutulur; bir bağlantı aynı karşılaştırmayı başkası için de açar.",
  "about.decode.title": "Bir model adı nasıl okunur",
  "about.decode.p1": "Açık ağırlıklı bir modelin adı, birbirinden bağımsız birkaç kararı tek bir dizede toplar: aile ve sürüm, boyut, mimari, hangi amaçla eğitildiği, nasıl quantize edildiği ya da paketlendiği. Çözücü organizasyonu eğik çizginin önünden alır, gerisini tire ve alt çizgilerden böler ve her parçayı bu kategorilerin kurallarıyla sırayla eşleştirir.",
  "about.decode.p2": "Parametre sayılarını (8B, 350M), Mixture-of-Experts boyutlarını (8x7B) ve aktif parametreleri (A3B); quantization ve formatları (AWQ, GPTQ, GGUF ve Q seviyeleri, FP8, NVFP4 ve MXFP4, BF16, W4A16, INT4, bitsandbytes 4-bit); eğitim türlerini (Instruct, Chat, Base, Coder, Math, VL, Embedding, Reranker ve R1, QwQ, Thinking gibi akıl yürütme adları); eğitim yöntemlerini (DPO, ORPO, GRPO, LoRA); context uzunluklarını (32k), tarihleri ve sürümleri tanır. Yalnızca adı okur — adlandırma gelenekleri aileden aileye değişir ve bir ad kendi içeriği hakkında yanılıyor olabilir.",
  "about.decode.q1": "Model adındaki A3B ne demek?",
  "about.decode.a1": "Mixture-of-Experts bir modelde token başına yaklaşık 3 milyar aktif parametre. Qwen3-30B-A3B 30 milyar parametre tutar ama her token'ı toplamı 3 milyar civarındaki uzmanlardan geçirir: bellek 30B'nin tamamı için gerekir, token başına hesaplama ise 3B'lik bir modelinkine yakındır.",
  "about.decode.q2": "GGUF, AWQ ve GPTQ arasındaki fark ne?",
  "about.decode.a2": "GGUF, llama.cpp ve onun üzerine kurulan araçların dosya formatıdır; genelde CPU, Apple Silicon ve tüketici GPU'ları için Q4, Q8 gibi quantization seviyeleri taşır. AWQ ve GPTQ ise safetensors olarak saklanan, vLLM gibi GPU servis motorlarını hedefleyen 4-bit ağırlık quantization yöntemleridir.",
  "about.decode.q3": "FP8, NVFP4 ve MXFP4 ne anlama geliyor?",
  "about.decode.a3": "BF16'dan küçük kayan noktalı ağırlık formatlarıdır. FP8 her ağırlığı bir byte'ta, BF16'nın yarısında saklar; NVFP4 ve MXFP4 ise ağırlık başına yarım byte'lık 4-bit formatlardır ve yeni NVIDIA donanımlarında, gpt-oss gibi modellerde kullanılır.",
  "about.decode.q4": "Instruct ile Base arasındaki fark ne?",
  "about.decode.a4": "Base model yalnızca metni sürdürmek üzere ön eğitimden geçmiştir. Instruct model — Chat ya da -it adıyla da görülür — talimatlara uymak ve sohbet sürdürmek için ayrıca eğitilmiştir; çoğu uygulamanın istediği de budur.",
  "about.vllm.title": "vllm serve bayrakları nasıl seçiliyor",
  "about.vllm.p1": "Bir model, bir GPU ve adedi, bir context uzunluğu, bir öncelik (dengeli, throughput, düşük gecikme, maks doğruluk ya da bellek-kısıtlı) ve bir görev (sohbet, RAG, kod, araç kullanımı, yapısal JSON, görsel ya da akıl yürütme) seç. Yardımcı bunu, her bayrak için tek satırlık gerekçesiyle bir vllm serve komutuna ve aynı bayrakların Kubernetes args biçimine dönüştürür.",
  "about.vllm.f1": "--max-model-len = seçtiğin context",
  "about.vllm.f2": "--tensor-parallel-size = GPU sayısı; MoE modellerde ayrıca --enable-expert-parallel",
  "about.vllm.f3": "--gpu-memory-utilization = throughput ya da bellek-kısıtlı öncelikte 0.95, diğerlerinde 0.90",
  "about.vllm.f4": "--kv-cache-dtype fp8 = bellek-kısıtlı ya da throughput önceliğinde, 32k+ context ya da RAG görevinde",
  "about.vllm.f5": "--max-num-seqs = 512 (throughput), 32 (düşük gecikme) ya da 64 (bellek-kısıtlı); en fazla ⌊((GPU × VRAM × utilization − 1 GiB) ÷ 1,1 − ağırlıklar) ÷ dizi başına KV⌋",
  "about.vllm.f6": "--enable-prefix-caching: sohbet, RAG, araç kullanımı ve akıl yürütmede; --enable-chunked-prefill: uzun context'te",
  "about.vllm.p2": "Araç kullanımı, modelin ailesine uygun tool-call ayrıştırıcısıyla --enable-auto-tool-choice ekler; yapısal JSON xgrammar arka ucunu ekler, görsel görev prompt başına görsel sayısını sınırlar. Önceden quantize edilmiş depolar (AWQ, GPTQ, FP8, NVFP4) --quantization bayrağı gerektirmez ve sayfa bunu belirtir. Bellek kontrolü — ağırlıklar artı tam uzunlukta bir dizinin KV cache'i, × 1,1, + 1 GiB — model sığmayacaksa uyarır; VRAM hesaplayıcısından kabadır, kesin boyutlandırma için onu kullan. vLLM'in Metal arka ucu olmadığı için Apple cihazları listede yoktur.",
  "about.vllm.q1": "--gpu-memory-utilization ne işe yarar?",
  "about.vllm.a1": "vLLM'in her GPU'da model ağırlıkları, aktivasyonlar ve KV cache için alabileceği bellek oranıdır. Ağırlıkların kullanmadığı kısım KV cache olur; değer yükseldikçe daha çok eşzamanlı dizi sığar ve karttaki başka işlere daha az pay kalır.",
  "about.vllm.q2": "--max-num-seqs neden beklediğimden düşük?",
  "about.vllm.a2": "Yardımcı onu, seçtiğin context uzunluğunda KV cache'in gerçekten tutabileceği sayıyla sınırlar. Daha yüksek ayarlamak kapasite eklemez: o noktadan sonraki istekler kuyrukta bekler.",
  "about.vllm.q3": "FP8 KV cache kullanmalı mıyım?",
  "about.vllm.a3": "KV cache'i yarıya indirir, yani yaklaşık iki kat dizi sığar; ama uzun context'li işlerde doğruluğa mal olabilir. Yardımcının onu yalnızca bellek ya da throughput öncelikliyken ve context uzunken önermesi, önce doğrulamanı istemesi bu yüzdendir.",
  "about.vllm.q4": "Tensor parallel için kaç GPU gerekir?",
  "about.vllm.a4": "Ağırlıkların ve iş yükünün KV cache'inin sığacağı kadar. Buradaki bellek kontrolü kaç tane gerektiğini tahmin eder; VRAM hesaplayıcısı kart başına kesin değeri gösterir ve modelin key-value head'lerini eşit bölen bir GPU sayısı önerir.",
};

/** Both dictionaries. Exported so scripts/test-invariants.ts can diff them. */
export const DICTS: Record<Lang, Dict> = { en, tr };

export function translate(lang: Lang, key: string, vars?: Record<string, string | number>): string {
  let s = DICTS[lang][key] ?? DICTS.en[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      s = s.replaceAll(`{${k}}`, String(v));
    }
  }
  return s;
}

